(ns ehrt.docs-tooling.docsgen-test
  "Covers docs/cli.md's renderer (DOC-3). The real staleness guard is
  CI's generated-doc freshness step (.github/workflows/test.yml's
  \"generated-doc freshness (regen + diff)\" step, P1-2, 2026-07-31
  review catch-up: `make docsgen` then `git diff --exit-code` on all
  four generated docs, per push); these tests cover what that step
  can't -- that the renderer actually emits every spec'd group/verb/
  flag, rather than emitting a well-formed page that happens to be
  missing half its data.

  Split out of the former ehrt.tools.docsgen-test (docs-tooling
  extraction, 2026-07-31, refactoring-review stage 1) alongside the
  namespace it covers: the operators.md half of the original test file
  moved to components/corpus/test/ehrt/corpus/operators_doc_test.clj
  instead, since the renderer it covers stayed behind in the domain
  component (ehrt.corpus.operators-doc) -- see that namespace's own
  docstring and ADR-0016 for why the split happened.
  escape-cell/banner are covered again here, against this component's
  own duplicate copy of those two helpers, not because the assertions
  themselves changed."
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [ehrt.docs-tooling.docsgen :as docsgen]))

;; ---- test-cli-spec: a representative fixture, not the real cli-spec ----
;;
;; render-cli-md is pure (spec -> markdown string); it has no compile-time
;; dependency on bases/cli's help.clj (components never depend on
;; bases -- Polylith's direction is the reverse, notes/ADRs.md ADR-0002),
;; so these tests exercise the renderer against a small, representative
;; spec of the same shape rather than importing the live one. The real
;; spec's own freshness against docs/cli.md is CI's generated-doc
;; freshness step (.github/workflows/test.yml, per this file's own top
;; docstring) -- these tests were never that check; they prove the
;; renderer doesn't silently drop a group/verb/flag/exit-code that
;; *is* in whatever spec it's given.

(def test-cli-spec
  {:program "ehr"
   :exit-codes [{:code 0 :meaning "ran and passed"}
                {:code 1 :meaning "ran and legitimately rejected"}]
   :global-flags [{:flag "--json" :doc "emit a JSON projection" :default nil}]
   :groups [{:group "check" :doc "golden-equivalence judge"
             :positional "PATH" :positional-doc "a file or directory to check"
             :flags [{:flag "--expected" :doc "the corpus to compare against" :default nil}]}
            {:group "corpus" :doc "corpus construction"
             :verbs [{:verb "generate" :doc "generate a corpus"
                      :flags [{:flag "--seed" :doc "RNG seed" :default "1"}]}
                     {:verb "mutate" :doc "inject a controlled defect"
                      :positional "PATH" :positional-doc "a file or directory to mutate"
                      :flags []}]}]})

(defn- command-pairs
  [spec]
  (vec (mapcat (fn [g]
                 (if (:verbs g)
                   (map (fn [v] [(:group g) (:verb v)]) (:verbs g))
                   [[(:group g) nil]]))
               (:groups spec))))

;; ---- shared helpers (this half's own duplicate copy) ----

(deftest escape-cell-escapes-table-delimiters-test
  (is (= "a \\| b" (docsgen/escape-cell "a | b"))))

(deftest banner-names-its-target-and-what-to-edit-instead-test
  (let [b (docsgen/banner "cli-doc" "the spec" "Edit the spec.")]
    (is (str/starts-with? b "<!-- GENERATED by `make cli-doc` from the spec -- do not hand-edit."))
    (is (str/includes? b "Edit the spec."))))

;; ---- docs/cli.md ----

(deftest cli-md-names-every-group-and-verb-in-the-spec-test
  (let [md (docsgen/render-cli-md test-cli-spec)]
    (doseq [[group verb] (command-pairs test-cli-spec)]
      (if verb
        (is (str/includes? md (str "### `ehrt " group " " verb "`"))
            (str group " " verb " must get its own section"))
        (is (str/includes? md (str "## `ehrt " group "`"))
            (str group " must get its own section"))))))

(deftest cli-md-lists-every-flag-the-spec-declares-test
  (let [md (docsgen/render-cli-md test-cli-spec)
        spec-flags (concat (:global-flags test-cli-spec)
                           (mapcat (fn [g] (concat (:flags g) (mapcat :flags (:verbs g))))
                                   (:groups test-cli-spec)))]
    (is (seq spec-flags))
    (doseq [{:keys [flag doc]} spec-flags]
      (is (str/includes? md (str "`" flag "`")) (str flag " must appear"))
      (is (str/includes? md (docsgen/escape-cell doc)) (str flag "'s doc must appear")))))

(deftest cli-md-carries-the-exit-code-table-test
  (let [md (docsgen/render-cli-md test-cli-spec)]
    (doseq [{:keys [code meaning]} (:exit-codes test-cli-spec)]
      (is (str/includes? md (str "| `" code "` |")) (str "exit code " code " must appear"))
      (is (str/includes? md meaning)))))

(deftest cli-md-documents-positional-conventions-where-the-spec-declares-them-test
  (let [md (docsgen/render-cli-md test-cli-spec)]
    (doseq [g (:groups test-cli-spec)
            :when (:positional g)]
      (is (str/includes? md (str "**Positional argument `" (:positional g) "`**"))
          (str (:group g) " must document its positional argument"))
      (is (str/includes? md (:positional-doc g))))))

(deftest cli-md-carries-banner-and-pre-release-notice-test
  (let [md (docsgen/render-cli-md test-cli-spec)]
    (is (str/starts-with? md "<!-- GENERATED by `make cli-doc`"))
    (is (str/includes? md docsgen/pre-release-notice))))

(deftest cli-md-defers-worked-examples-to-the-other-reference-pages-test
  (testing "the author ruling: cli.md carries the surface, not walkthroughs"
    (let [md (docsgen/render-cli-md test-cli-spec)]
      (is (str/includes? md "(use-cases.md)"))
      (is (str/includes? md "(formats.md)"))
      (is (str/includes? md "(operators.md)"))
      (is (str/includes? md "(locators.md)")))))

(deftest cli-md-render-is-pure-and-idempotent-test
  (is (= (docsgen/render-cli-md test-cli-spec)
         (docsgen/render-cli-md test-cli-spec))))
