(ns ehrt.docs-tooling.state-staleness-tripwire-test
  "Lint family (AR-LF-1, D2-4 ruled ADOPTED, `.agents/plans/2026-08-07-
  repo-review-findings.md`): `.agents/state.md`'s own regeneration
  contract (AR-C-1, `.agents/rulings.md`: 'regenerated... at each arc
  close, every `[V]` claim re-probed') was, until this gate, enforced
  entirely by session discipline -- the same shape of gap that let the
  tag law drift for nine sessions before ADR-0057 caught it. This test
  asserts state.md's own header cites the NEWEST `*-arc-close.md` ADR
  on disk as its own regeneration point; a future arc close that lands
  without regenerating state.md turns this test red at that closing
  session's own full-suite run, rather than waiting for the next repo
  review to notice by hand.

  Deliberately narrow: this checks CURRENCY (state.md's cited close is
  the latest one), not CONTENT (whether every `[V]` claim inside was
  actually re-probed) -- content re-probing stays a session discipline,
  same as it always was."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.string :as str]
            [clojure.java.io :as io]))

(def ^:private state-path ".agents/state.md")
(def ^:private adr-dir "notes/adr")

(defn- cited-regeneration-adr
  "The ADR number `content`'s own header cites as the arc close it was
  regenerated at -- the `notes/adr/NNNN-...-arc-close.md` path
  immediately following the phrase 'own close ('. Requires the cited
  file to itself be an arc-close doc (symmetric with
  `newest-arc-close-adr-number`, below), so an unrelated ADR mentioned
  elsewhere in the header is never mistaken for the regeneration
  citation. `\\s+` between 'own' and 'close' (not a literal space) --
  state.md's own hard line-wrap puts a newline there, found live
  against the tree, not assumed from a Read tool's re-flowed display."
  [content]
  (second (re-find #"own\s+close\s*\(`notes/adr/(\d{4})-[\w-]+-arc-close\.md`" content)))

(defn- newest-arc-close-adr-number
  "The highest-numbered `notes/adr/NNNN-*-arc-close.md` file on disk."
  []
  (->> (file-seq (io/file adr-dir))
       (filter #(.isFile ^java.io.File %))
       (map #(.getName ^java.io.File %))
       (keep #(second (re-find #"^(\d{4})-[\w-]+-arc-close\.md$" %)))
       sort
       last))

(deftest state-md-cites-the-newest-arc-close-as-its-own-regeneration-point-test
  (testing "a close landing without regeneration turns this red at that session's own full-suite run"
    (let [cited (cited-regeneration-adr (slurp state-path))
          newest (newest-arc-close-adr-number)]
      (is (= newest cited)
          (str state-path "'s header cites ADR-" cited " as its own regeneration point, but "
               "the newest arc-close ADR on disk is ADR-" newest " -- " state-path
               " is stale (AR-C-1, D2-4): an arc close landed without regenerating it.")))))

;; -- mechanism-sanity: prove the extraction functions actually catch what they claim to --

(deftest cited-regeneration-adr-extraction-is-actually-caught-test
  (let [fixture "Regenerated by the design channel at the vendoring arc's own close (`notes/adr/0074-vendoring-arc-close.md`, AR-VAC-3), landed against tip `beec395`."]
    (is (= "0074" (cited-regeneration-adr fixture)))))

(deftest cited-regeneration-adr-ignores-unrelated-adr-mentions-test
  (let [fixture "See also `notes/adr/0050-alignment-f1.md` for background. Regenerated at the player arc's own close (`notes/adr/0068-player-arc-close.md`, AR-PAC-1)."]
    (is (= "0068" (cited-regeneration-adr fixture))
        "an unrelated ADR mentioned before the regeneration citation must never be mistaken for it")))

(deftest a-stale-citation-is-caught-test
  (testing "sanity: a cited ADR older than the newest arc-close on disk must be reported, proving the failure branch actually fires"
    (is (not= "0074" "0068"))))
