(ns ehrt.docs-tooling.state-derived-test
  "Parity gate for the generated half of the continuity register
  (compression arc session D, `notes/adr/0147-compression-arc-close.md`).

  Same shape as `ehrt.docs-tooling.adr-index-test`'s own (ADR-0143):
  the committed file must equal what the renderer produces from the
  live tree RIGHT NOW, so a session that changes the tree without
  regenerating is red here as well as in CI's freshness diff. The two
  are not redundant -- CI's diff catches it on push, this catches it in
  the full-suite run a session makes before pushing, which is where a
  session actually looks.

  Below the parity gates sit mechanism-sanity cases for every parser
  `ehrt.docs-tooling.state-derived` carries, over synthetic fixtures
  rather than the live tree. This is not ceremony: a parser that
  matches nothing renders `0`, `0` reads as a fact about the repo, and
  no parity gate can tell the difference because the renderer and the
  committed file would agree on the same wrong number. The oracle-root
  parser is the specimen -- it reads a `def` form out of 400+ lines of
  source whose docstrings mention root names in prose."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.string :as str]
            [clojure.java.io :as io]
            [ehrt.docs-tooling.state-derived :as sd]))

;; -- the parity gates, over the live tree --

(deftest state-derived-md-matches-a-fresh-render-test
  (testing ".agents/state-derived.md is exactly what the renderer produces from the tree today"
    (is (= (sd/render (sd/collect)) (slurp ".agents/state-derived.md"))
        (str ".agents/state-derived.md is stale -- run `make docsgen` (or `make state-derived`) "
             "and commit the result. Every number on that page is derived; a hand edit here is "
             "reverted by the next regeneration and fails CI's freshness diff in the meantime."))))

(deftest every-generated-record-index-matches-a-fresh-render-test
  (testing "each INDEX.md is exactly its own directory's listing, rendered"
    (doseq [{:keys [dir] :as target} sd/index-targets]
      (is (= (sd/render-index (assoc target :files (sd/index-files dir)))
             (slurp (io/file dir "INDEX.md")))
          (str dir "/INDEX.md is stale -- a file was added or removed without regenerating. "
               "Run `make state-derived`. `bin/close-scaffold` does this for you.")))))

(deftest a-generated-index-never-indexes-itself-or-its-readme-test
  (testing "INDEX.md and README.md are not records and must never appear as rows"
    (doseq [{:keys [dir]} sd/index-targets]
      (let [files (sd/index-files dir)]
        (is (not-any? #{"INDEX.md" "README.md"} files)
            (str dir "/INDEX.md would list itself or its own README as a record"))))))

;; -- shape: the derived page says what it is, and carries every section --

(deftest state-derived-declares-itself-generated-test
  (let [content (slurp ".agents/state-derived.md")]
    (testing "the house generated-file banner, so no one hand-edits it"
      (is (str/starts-with? content "<!-- GENERATED by `make state-derived`")))
    (testing "every section a reader is pointed at from state.md actually exists"
      (doseq [heading ["## Workspace shape" "## Vendored GMF content" "## Test surface"
                       "## Registers" "## Reading sets"]]
        (is (str/includes? content heading)
            (str "state-derived.md has no " heading " section"))))))

(deftest the-derived-register-carries-no-stale-marked-claim-test
  (testing "`[V @sha]` was state.md's own 'probe-verified at this landing' tag -- a derived page cannot carry one, because it is not verified AT a landing, it is re-derived at every one"
    (is (not (re-find #"\[V @" (slurp ".agents/state-derived.md"))))))

;; -- the tag census is deliberately absent (the namespace docstring says why) --

(deftest the-derived-register-does-not-count-tags-test
  (testing "a tag is pushed after the commit that would record it, so a generated tag count fails CI's freshness diff on the next push -- it stays a command in state.md's hand-owned half"
    (is (not (str/includes? (slurp ".agents/state-derived.md") "stable-*"))
        "state-derived.md renders a stable-* tag figure; that number is wrong the moment it lands")))

;; -- mechanism sanity: every parser actually catches what it claims to --

(def ^:private roots-fixture
  "A `roots` map in digest.clj's own exact shape -- first key on the
  opening-brace line, last key closing the map with `})` -- preceded by
  a comment that MENTIONS a root name in prose and followed by a
  docstring containing both a brace pair and a line that begins with a
  complete quoted phrase. Every one of those is a false positive some
  earlier draft of the parser actually took."
  (str ";; Verifying this session's own claim that the SIX pre-existing roots\n"
       ";;   \"not-a-root-just-prose\" is discussed here\n"
       "(def ^:private roots\n"
       "  {\"appendicitis\"                       appendicitis-batch\n"
       "   \"sore-throat\"                        sore-throat-batch\n"
       "   \"ear-infections-engine\"              ear-infections-engine-pair})\n"
       "\n"
       "(defn -main\n"
       "  \"Writes one <root>.edn per root, the {:ground-truth :hl7} pair --\n"
       "  \"phantom-root-in-a-docstring\" would be read as a key by a scan\n"
       "  that does not stop where the map does.\"\n"
       "  [out-dir] nil)\n"))

(deftest oracle-root-parsing-is-actually-caught-test
  (testing "the first key shares the opening brace's line and must not be dropped"
    (is (= ["appendicitis" "sore-throat" "ear-infections-engine"]
           (sd/parse-oracle-roots roots-fixture))))
  (testing "prose above the form is excluded"
    (is (not-any? #{"not-a-root-just-prose"} (sd/parse-oracle-roots roots-fixture))))
  (testing "the scan stops where the map closes, even though the closing brace shares the last key's line"
    (is (not-any? #{"phantom-root-in-a-docstring"} (sd/parse-oracle-roots roots-fixture))
        "a scan that runs past `})` reads the docstring below as more roots")))

(deftest oracle-root-parsing-is-not-vacuous-on-the-live-file-test
  (testing "a parser that silently matched nothing would render 0 roots and 0 would read as a fact"
    (let [roots (sd/parse-oracle-roots (slurp "components/oracle/src/ehrt/oracle/digest.clj"))]
      (is (seq roots) "parsed zero oracle roots out of the live digest.clj -- the parser has drifted from the form it reads")
      (is (apply distinct? roots) "duplicate oracle root key parsed -- the scan window is wrong")
      (is (every? #(re-matches #"[a-z0-9-]+" %) roots)))))

(deftest roadmap-row-parsing-is-actually-caught-test
  (let [fixture (str "# Roadmap\n\n## Next (backlog)\n"
                     "- OPEN **[a]** PRIORITY 1 -- one\n"
                     "  continuation line that is not a row\n"
                     "- DEFERRED (trigger: x) **[b]** PRIORITY 2 -- two\n"
                     "\n## Done (current arc only)\n"
                     "- CLOSED 2026-08-17 ADR-0147 **[c]**\n")]
    (is (= [{:section "Next" :token "OPEN"}
            {:section "Next" :token "DEFERRED"}
            {:section "Done" :token "CLOSED"}]
           (sd/parse-roadmap-rows fixture))
        "a row's continuation lines must not count as rows, and each row must land in its own section")))

(deftest rulings-row-parsing-is-actually-caught-test
  (let [fixture (str "- **R-alpha** -- a rule -- ADR-0001\n"
                     "- **R-beta** -- another rule -- ADR-0002\n"
                     "  SUPERSEDED-BY R-alpha (ADR-0003)\n"
                     "not a row at all\n")]
    (is (= ["alpha" "beta"] (map :slug (sd/parse-rulings-rows fixture))))))

(deftest line-count-is-the-budget-gates-own-measurement-test
  (testing "one definition: the number this register renders and the number the budget gate enforces are the same measurement"
    (is (= (sd/line-count ".agents/rulings.md")
           (count (str/split-lines (slurp ".agents/rulings.md")))))
    (is (= (sd/total-lines [".agents/rulings.md" ".agents/state.md"])
           (+ (sd/line-count ".agents/rulings.md") (sd/line-count ".agents/state.md"))))))
