(ns ehrt.docs-tooling.traces-fresh-test
  "ADR-0149, closing `roadmap.md#demos-traces-ungated`. `demos/traces/**`'s
  seven committed `messages*.txt`, six `ground-truth.edn` and one FHIR
  bundle are produced by `bin/ehrt sim run` and were regenerated by
  nothing -- no `Makefile` target, no workflow, no test, only
  `.gitattributes:27`'s `-text` byte protection (ADR-0142's own \"Gating
  verified negative\" census). They drifted silently and did: ADR-0142
  found `order-result/messages.txt` captured before PV1 gained its
  trailing positional fields, and ADR-0149's own Step 0 census found
  `module-mix/messages.txt` was never its own README command's output at
  all -- proven by re-running that command at `f07684c`, the commit that
  last wrote the file, and getting today's bytes rather than the
  committed ones.

  Four claims, each red at 922e55a:

  (a) POPULATION CLOSURE -- every `demos/traces/*/README.md` the tree
      holds is an `exercised-sources.edn` row. Enumerated from the tree,
      diffed against the register (`rulings.md#R-population-closure`);
      a seventh trace directory added tomorrow is red here until it is
      registered. Registration is what gates it, because ADR-0148's
      `exercised-sources-coverage-test` runs `check-all` over the whole
      register -- so this namespace never re-checks freshness itself
      (`rulings.md#R-exercised-implies-gated`, satisfied by feeding the
      existing gate rather than adding a parallel one).

  (b) PINNED TAUGHT-COMMAND COUNTS -- how many command lines each trace
      README actually teaches. Freshness alone cannot see a README losing
      a fence and its script losing the same fence in one edit: both
      sides move together and the check stays green over a shrinking
      population. The pins are `strip-fresh/reject-vacuous`'s absent-
      population guard (ADR-0148) sharpened from \"more than zero\" to
      the real number.

  (c) THE MAKE GRAPH -- `docsgen` depends on `traces`, and `traces` runs
      `bin/regen-traces`. A regeneration target nothing calls is the same
      ungated state one layer up.

  (d) THE CI DIFF LIST -- `.github/workflows/test.yml`'s freshness step
      diffs `demos/traces/`. That workflow's own comment has said since
      ADR-0136 that a new derived file \"goes on a make target AND on the
      diff list below, same commit\"; nothing asserted it. (c) and (d)
      together are that sentence made mechanical.

  PREMISE CORRECTED, disclosed (ADR-0149 Step 1). The session prompt put
  this population assertion in `docsgen-test`, \"where the population
  lives.\" It lives neither there nor anywhere: `docsgen-test` covers
  `render-cli-md` only, and ADR-0136's widening of the CI diff list was
  prose discipline in a workflow comment, never a gate. (c) and (d) are
  the first mechanical check of either surface."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [ehrt.docs-tooling.demo-exerciser-fresh :as demo-fresh]
            [ehrt.docs-tooling.exercised-sources :as reg]
            [ehrt.docs-tooling.make-graph :as mg]
            [ehrt.docs-tooling.strip-fresh :as sf]))

(def ^:private traces-dir "demos/traces")
(def ^:private script "bin/regen-traces")
;; `makefile` / `workflow` / the two parsers below moved to
;; `ehrt.docs-tooling.make-graph` (ADR-0155): a third gate needed the same
;; parsers, and three byte-identical private copies is where a duplicated
;; parser starts to drift.

(defn- trace-readmes
  "Every `demos/traces/<name>/README.md` the tree holds, as repo-relative
  paths -- the population, enumerated from the tree. `demos/traces/
  README.md` itself is excluded on purpose: it is the tree's prose index,
  teaches no `bin/ehrt` command and derives no file."
  []
  (->> (.listFiles (io/file traces-dir))
       (filter #(.isDirectory ^java.io.File %))
       (map #(str traces-dir "/" (.getName ^java.io.File %) "/README.md"))
       (filter #(.exists (io/file %)))
       sort
       vec))

(defn- trace-rows []
  (filterv #(str/starts-with? (:source %) (str traces-dir "/")) (reg/load-registry)))

;; ---- (a) population closure ----

(deftest every-trace-readme-is-an-exercised-sources-row-test
  (let [registered (set (map :source (reg/load-registry)))
        in-tree (trace-readmes)
        unregistered (remove registered in-tree)]
    (is (pos? (count in-tree))
        "sanity: demos/traces must actually hold trace READMEs -- a silently empty population would make this gate vacuous")
    (is (empty? unregistered)
        (str "trace READMEs no exercised-sources row gates -- each one's derived files "
             "(messages*.txt, ground-truth.edn) can drift from the command the README "
             "teaches, silently, exactly as ADR-0142 and ADR-0149 each found:\n  "
             (str/join "\n  " unregistered)))))

(deftest every-trace-row-names-the-one-regeneration-script-test
  (let [rows (trace-rows)]
    (is (= (count (trace-readmes)) (count rows))
        "one row per trace README, no more: a second row for one trace would gate the same taught block twice and hide which block moved")
    (is (every? #(= script (:script %)) rows)
        (str "every trace row is exercised by " script " -- one script carrying one marker "
             "pair per trace, so a single `make traces` regenerates the whole tree:\n  "
             (pr-str (mapv (juxt :source :script) rows))))
    (is (= (count rows) (count (set (map :marker-open rows))))
        "each trace's marker pair must be distinct, or two traces' taught blocks cross-match inside the one script")))

;; ---- (b) pinned taught-command counts ----

(def ^:private taught-command-counts
  "Per trace README, how many command lines `demo-exerciser-fresh`'s
  extraction finds -- counting each backslash continuation line
  separately, the unmerged-continuation convention that namespace
  documents. Probed live at 922e55a, before `bin/regen-traces` existed."
  {"demos/traces/boarding-transfer/README.md" 1
   "demos/traces/emit-state/README.md" 4
   "demos/traces/module-mix/README.md" 1
   "demos/traces/order-result/README.md" 2
   "demos/traces/persona-enriched/README.md" 2
   "demos/traces/site-profiles/README.md" 2})

(deftest the-pinned-counts-name-every-trace-readme-test
  (is (= (set (trace-readmes)) (set (keys taught-command-counts)))
      "the pin map and the tree must name the same READMEs -- a pin for a README the tree no longer holds, or a README with no pin, is the pin going stale rather than the doc"))

(deftest each-trace-readme-teaches-its-pinned-number-of-commands-test
  (doseq [[readme expected] (sort taught-command-counts)]
    (testing readme
      (let [row (first (filter #(= readme (:source %)) (reg/load-registry)))
            readme-lines (demo-fresh/readme-command-lines readme)
            script-lines (when row
                           (sf/script-command-lines script (:marker-open row) (:marker-close row)))]
        (is (= expected (count readme-lines))
            (str readme " teaches " (count readme-lines) " command lines, pinned at " expected
                 " -- a fence added or removed here moves a committed trace file, so the pin moves with the ADR that moves the trace"))
        (is (some? row)
            (str "no exercised-sources row for " readme " -- nothing names the marker pair its taught block lives behind"))
        (is (= expected (count script-lines))
            (str script "'s block for " readme " carries " (count script-lines) " lines, pinned at "
                 expected " -- freshness proves the two sides teach the SAME commands; this proves neither side quietly shrank to nothing in step"))))))

;; ---- (c) the make graph ----

(deftest docsgen-depends-on-the-traces-target-test
  (let [text (slurp mg/makefile)]
    (is (some #{"traces"} (mg/target-prerequisites text "docsgen"))
        (str "`make docsgen` must depend on `traces`, or demos/traces is regenerated only by "
             "a target CI never runs. docsgen prerequisites today: "
             (pr-str (mg/target-prerequisites text "docsgen"))))
    (is (some? (mg/target-prerequisites text "traces"))
        "a `traces:` rule must exist")
    ;; Booleans, not `str/includes?` on the Makefile itself: clojure.test
    ;; renders both arguments of a failing form, and the whole Makefile in
    ;; a failure message buries the one sentence the reader needs.
    (is (true? (str/includes? text (str "traces:\n\t" script)))
        (str "`traces:` must run " script " as its first recipe line"))
    (is (true? (some? (some #{"traces"} (str/split (first (str/split-lines text)) #"\s+"))))
        "`traces` must be .PHONY -- it regenerates demos/traces/**, never a file named `traces`")))

;; ---- (d) the CI diff list ----

(deftest the-ci-freshness-step-diffs-the-traces-tree-test
  (let [paths (mg/freshness-diff-paths (slurp mg/workflow))]
    (is (pos? (count paths))
        "sanity: the freshness step must actually name paths -- if this returns none the extractor broke and the claim below is silently vacuous")
    (is (some #{"demos/traces/"} paths)
        (str "`demos/traces/` must be on CI's freshness diff list, or `make traces` regenerates "
             "a tree nothing compares and the ungated state ADR-0142 recorded survives one "
             "target later. Diffed paths today: " (pr-str paths)))))
