(ns ehr-testing-tools.cli.help
  "The `ehr help` surface's data (DOC-1): one spec structure describing
  every group/verb, its flags, its positional-argument convention, and
  the shared exit-code table -- rendered to plain text by the pure
  functions below. The spec does not drive argument parsing (`cli/parse`
  is untouched this session); it exists so the help text and a coverage
  test can both walk the same data instead of drifting independently.
  `cli-spec` is this session's ground truth for the CLI surface,
  enumerated from source in DOC-1 Step 0 (see that session's commit
  history for the read-from-source inventory this spec is built from)."
  (:require [clojure.string :as str]))

(def exit-codes
  "0/1/2/3 per ADR-0004's ok/rejected/error mapping, extended by
  ADR-0010 for the no-verdict arm -- see `cli/result->exit-code`'s own
  docstring for the authoritative reasoning; this table only cites it."
  [{:code 0 :meaning "ran and passed"}
   {:code 1 :meaning "ran and legitimately rejected"}
   {:code 2 :meaning "operational error (bad invocation, missing artifact, subprocess failure, etc.)"}
   {:code 3 :meaning "a gate's aggregate contains :no-verdict under the default --treat-no-verdict-as policy (ADR-0010)"}])

(def global-flags
  [{:flag "--json" :doc "project the EDN result to JSON (EDN remains canonical)"}
   {:flag "--help" :doc "print this command's usage and exit 0 without running it"}])

(def ^:private artifact-flags
  [{:flag "--name" :doc "artifact name, e.g. \"synthea\""}
   {:flag "--version" :doc "artifact version, e.g. \"4.0.0\""}
   {:flag "--lockfile" :doc "path to the lockfile" :default "artifacts.lock.edn"}])

(def ^:private gate-common-flags
  [{:flag "--path" :doc "alternative to the positional PATH"}
   {:flag "--report" :doc "write the report EDN to this path"}
   {:flag "--baseline" :doc "baseline-relative mode: path to a previous --report EDN; only genuinely new findings count"}
   {:flag "--treat-no-verdict-as" :doc "\"pass\" or \"rejected\" -- folds :no-verdict into an existing polarity (ADR-0010)"}])

(def cli-spec
  {:program "ehr"
   :exit-codes exit-codes
   :global-flags global-flags
   :groups
   [{:group "artifact"
     :doc "Fetch and resolve locked external engine/tool artifacts (ADR-0005)."
     :verbs
     [{:verb "fetch" :doc "Fetch a locked artifact into the local content-addressed cache."
       :flags artifact-flags}
      {:verb "resolve" :doc "Resolve an already-fetched artifact to a filesystem path."
       :flags artifact-flags}]}

    {:group "corpus"
     :doc "Generate, mutate, intake, and inspect synthetic corpora."
     :verbs
     [{:verb "generate" :doc "Generate a deterministic synthetic Synthea corpus."
       :flags [{:flag "--config-path" :doc "Synthea properties file"}
               {:flag "--seed" :doc "patient-generation seed (integer)"}
               {:flag "--clinician-seed" :doc "clinician-generation seed (integer) -- required: Synthea defaults this to wall-clock time otherwise, which breaks reproducibility even with --seed pinned"}
               {:flag "--population" :doc "population size (integer)"}
               {:flag "--reference-date" :doc "generation reference date, YYYYMMDD -- required: Synthea otherwise generates relative to wall-clock \"now\""}
               {:flag "--output-dir" :doc "output directory for the corpus + manifest.edn"}
               {:flag "--locale" :doc "BCP47-ish locale" :default "en-US"}
               {:flag "--timezone" :doc "timezone" :default "UTC"}
               {:flag "--java-bin" :doc "java executable to invoke" :default "resolved via the artifact registry"}]}
      {:verb "mutate" :doc "Apply one mutation operator at one locator to every matching file under --input."
       :flags [{:flag "--input" :doc "a file, or a directory of files sharing one locator's shape"}
               {:flag "--operator-id" :doc "registered operator id -- see `ehr corpus operators`"}
               {:flag "--operator-version" :doc "operator version" :default "1"}
               {:flag "--locator-path" :doc "format-specific locator string (FHIR data-path, or v2 segment/field grammar)"}
               {:flag "--output-dir" :doc "directory for mutants + a lineage/ sidecar subdirectory"}]}
      {:verb "intake" :doc "Catalog a foreign (not generated by this repo) corpus batch."
       :flags [{:flag "--source-dir" :doc "directory of files to catalog"}
               {:flag "--label" :doc "source label for the intake record"}
               {:flag "--out" :doc "catalog output path"}
               {:flag "--received" :doc "received date, YYYY-MM-DD" :default "today"}]}]}

    {:group "gate"
     :doc "Conformance-gate a file or directory against HL7 v2 or FHIR."
     :positional "PATH"
     :positional-doc "a file or directory, given as a trailing positional argument, not --path -- an explicit --path is never overridden by it"
     :verbs
     [{:verb "v2" :doc "Gate against HL7 v2 base-structural conformance (HAPI)."
       :flags gate-common-flags}
      {:verb "fhir" :doc "Gate against FHIR base-spec conformance (the official validator)."
       :flags (into gate-common-flags
                    [{:flag "--lockfile" :doc "path to the lockfile" :default "artifacts.lock.edn"}
                     {:flag "--out-dir" :doc "validator scratch directory" :default "target/gate-fhir"}
                     {:flag "--java-bin" :doc "java executable to invoke"}])}]}

    {:group "check"
     :doc "Check a candidate corpus against an expected corpus and/or explicit per-file assertions -- the corpus's second judge, alongside Gate."
     :positional "DIR"
     :positional-doc "check has no sub-verb: the second positional argument names the candidate directory directly"
     :flags [{:flag "--path" :doc "alternative to the positional DIR"}
             {:flag "--expected" :doc "expected-corpus directory (golden equivalence)"}
             {:flag "--assertions" :doc "path to an EDN file of assertion maps" :default "[{:kind :matches-expected}] when --expected is given"}
             {:flag "--canonicalizers" :doc "ordered \"id@version,id2@version2\" list" :default "none"}
             {:flag "--pair-by" :doc "\"path\" or \"hash\"" :default "path"}
             {:flag "--report" :doc "write the report EDN to this path"}]}]})

(defn group-names
  "Every group name in the spec, in declared order."
  [spec]
  (mapv :group (:groups spec)))

(defn find-group
  [spec group-name]
  (first (filter #(= group-name (:group %)) (:groups spec))))

(defn verb-names
  "Verb names for a group, or nil for a group with no sub-verb (`check`)."
  [group]
  (some->> (:verbs group) (mapv :verb)))

(defn command-pairs
  "Every [group verb-or-nil] pair the spec declares -- verb is nil for a
  group with no sub-verb (`check`). This is the set a coverage test
  cross-checks against `dispatch`'s own routing, so a verb added to
  dispatch without a matching spec entry is a discoverable gap."
  [spec]
  (vec (mapcat (fn [g]
                 (if (:verbs g)
                   (map (fn [v] [(:group g) (:verb v)]) (:verbs g))
                   [[(:group g) nil]]))
               (:groups spec))))

(defn- render-flag
  [{:keys [flag doc default]}]
  (str "  " flag "  " doc (when default (str " (default: " default ")"))))

(defn- render-flags
  [flags]
  (if (seq flags)
    (str/join "\n" (map render-flag flags))
    "  (no flags)"))

(defn- render-exit-codes
  [exit-codes]
  (str/join "\n" (map (fn [{:keys [code meaning]}] (str "  " code "  " meaning)) exit-codes)))

(defn- render-verb
  [group-name {:keys [verb doc flags]}]
  (str "ehr " group-name " " verb "\n"
       "  " doc "\n\n"
       "Flags:\n" (render-flags flags)))

(defn render-group
  "Group usage text: `ehr help <group>` and `ehr <group> --help`. Returns
  nil for an unrecognized group name -- callers decide what that means."
  [spec group-name]
  (when-let [g (find-group spec group-name)]
    (str "ehr " group-name " -- " (:doc g) "\n"
         (when (:positional g)
           (str "\nPositional: " (:positional g) " -- " (:positional-doc g) "\n"))
         "\n"
         (if (:verbs g)
           (str/join "\n\n" (map #(render-verb group-name %) (:verbs g)))
           (str "Flags:\n" (render-flags (:flags g))))
         "\n\nExit codes:\n" (render-exit-codes (:exit-codes spec)))))

(defn render-top-level
  "The top-level usage text: bare `ehr`, `ehr help`, `--help` with no
  group. Always succeeds (the spec is static data, not user input)."
  [spec]
  (str "Usage: " (:program spec) " <group> [<verb>] [flags]\n\n"
       "Groups:\n"
       (str/join "\n" (map (fn [g] (str "  " (:group g) "  " (:doc g))) (:groups spec)))
       "\n\n"
       "Run `" (:program spec) " help <group>` for a group's verbs and flags.\n\n"
       "Global flags:\n" (render-flags (:global-flags spec))
       "\n\nExit codes:\n" (render-exit-codes (:exit-codes spec))))
