(ns ehr-testing-tools.corpus.intake
  "Intake capability (P5): foreign corpora -- files a consuming team
  brings from their own pipeline, not generated by this repo's own
  corpus.generate -- become first-class citizens of the same
  lineage/content-hash design generated corpora already use. Nursery
  #8 (corpus catalog): an index of corpus items (id, layer, format,
  lineage ref, tags); meaning lives in data, not filenames.

  Format sniffing is a cheap heuristic, not a validator: a file tagged
  :fhir-json here has merely been observed to parse as JSON with a
  top-level \"resourceType\" key -- judge.fhir, not this namespace, is
  what actually judges conformance. Content hashing is format-aware
  so an intaken FHIR file's catalog :id is *the same* hash
  corpus.mutate independently computes as a mutant's :parent -- no
  adapter, no translation layer between intake and mutation; the two
  consume the same content-identity function, so lineage chains
  across the intake/mutate boundary unchanged."
  (:require [clojure.data.json :as json]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [malli.core :as m]
            [ehr-testing-tools.digest :as digest]
            [ehr-testing-tools.corpus.mutate :as mutate]
            [ehr-testing-tools.result :as result])
  (:import [java.io File]))

(def known-source-formats #{:fhir-json :v2-er7 :unknown})

(def CatalogEntry
  [:map
   [:id [:re #"^[0-9a-f]{64}$"]]
   [:path :string]
   [:format (into [:enum] known-source-formats)]
   [:layer [:= :foreign]]
   [:source :string]
   [:received :string]])

(def IntakeRecord
  [:map
   [:source :string]
   [:date :string]
   [:file-count :int]
   [:catalog-hash [:re #"^[0-9a-f]{64}$"]]])

(defn valid-catalog-entry?
  [entry]
  (m/validate CatalogEntry entry))

(defn valid-intake-record?
  [record]
  (m/validate IntakeRecord record))

;; ---- format sniff: cheap heuristics, recorded not trusted ----

(defn- fhir-json?
  [content]
  (try
    (let [parsed (json/read-str content)]
      (and (map? parsed) (contains? parsed "resourceType")))
    (catch Exception _ false)))

(defn- v2-er7?
  "MSH-led ER7 encoding: an MSH segment starts with the literal \"MSH\"
  immediately followed by its own field separator (canonically \"|\",
  but ER7 allows any non-alphanumeric byte there) -- checking the 4th
  character is non-alphanumeric is enough to distinguish a real MSH
  segment from incidental text starting with the letters \"MSH\"."
  [content]
  (and (str/starts-with? content "MSH")
       (> (count content) 3)
       (not (Character/isLetterOrDigit (.charAt ^String content 3)))))

(defn sniff-format
  "Cheap, unvalidating format heuristic over a file's raw text content:
  :fhir-json (parses as JSON, top-level \"resourceType\" key present),
  :v2-er7 (starts with an MSH segment, ER7-encoded), or :unknown.
  Recorded, not trusted -- judge.fhir/judge.v2 are the actual judges of
  conformance; this only routes a file to the right catalog bucket."
  [content]
  (cond
    (fhir-json? content) :fhir-json
    (v2-er7? content) :v2-er7
    :else :unknown))

;; ---- content hash: format-aware, chains into corpus.mutate's own
;; content-identity function for the one format that already has one ----

(defn content-hash
  "The catalog :id for a file's content, dispatched by sniffed format.
  :fhir-json uses corpus.mutate/content-hash (sha256 of the parsed
  data's canonical-JSON serialization) -- the exact function
  corpus.mutate itself calls to compute a mutant's lineage :parent --
  so an intaken FHIR file's catalog id and its eventual mutant's
  :parent are the same value with no adapter. Every other format
  hashes the file's raw bytes directly: no canonical parsed form
  exists for v2 or unknown content yet (v2 mutation is P6)."
  [content format]
  (case format
    :fhir-json (mutate/content-hash (json/read-str content))
    (digest/sha256-string content)))

;; ---- intake! ----

(defn- source-files
  "Every regular file under dir, recursively, sorted by path for a
  deterministic catalog ordering -- foreign corpora may nest into
  subdirectories, unlike this repo's own flat generated output trees."
  [dir]
  (->> (file-seq (io/file dir))
       (filter #(.isFile ^File %))
       (sort-by #(.getPath ^File %))))

(defn- relative-path
  "file's path relative to source-dir, forward-slash-joined
  regardless of host path separator -- the catalog is a portable
  record, not tied to the orchestrating host's filesystem conventions."
  [source-dir file]
  (let [root (str (.getCanonicalPath (io/file source-dir)) File/separator)
        full (.getCanonicalPath ^File file)
        rel (if (str/starts-with? full root) (subs full (count root)) full)]
    (str/replace rel File/separator "/")))

(defn- catalog-entry
  [file source-dir source-label received]
  (let [content (slurp file)
        format (sniff-format content)]
    {:id (content-hash content format)
     :path (relative-path source-dir file)
     :format format
     :layer :foreign
     :source source-label
     :received received}))

(defn intake!
  "Catalogs every file under :source-dir as a foreign-corpus entry:
  content hash (format-aware, see `content-hash`), format sniff,
  {:layer :foreign :source source-label :received}. Writes
  :out/catalog.edn (the vector of entries) and :out/intake-record.edn
  (one batch record: source, date, file count, and the sha256 of the
  catalog file's own persisted bytes -- hashing what's actually
  written, same discipline as corpus.mutate's content-hash).

  :received is a required, explicit date string -- never read from
  the wall clock here, matching corpus.generate's :reference-date
  discipline (a required, explicit, pinned input rather than ambient
  state); the CLI shell is where wall-clock defaulting belongs, not
  this core function.

  Returns result/ok {:catalog [...] :intake-record {...} :out}."
  [{:keys [source-dir source-label out received]}]
  (let [files (source-files source-dir)
        catalog (mapv #(catalog-entry % source-dir source-label received) files)
        out-dir (io/file out)]
    (.mkdirs out-dir)
    (let [catalog-file (io/file out-dir "catalog.edn")]
      (spit catalog-file (pr-str catalog))
      (let [record {:source source-label
                    :date received
                    :file-count (count catalog)
                    :catalog-hash (digest/sha256-file catalog-file)}]
        (spit (io/file out-dir "intake-record.edn") (pr-str record))
        (result/ok {:catalog catalog :intake-record record :out out})))))
