(ns ehrt.tools.docsgen-test
  "Covers the two generated reference documents' renderers (DOC-3).
  The real staleness guard is CI's generated-doc freshness step
  (regenerate + `git diff --exit-code`); these tests cover what that
  step can't -- that the renderers actually emit every registered
  operator and every spec'd group/verb/flag, rather than emitting a
  well-formed page that happens to be missing half its data."
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [ehrt.tools.corpus.operators :as operators]
            [ehrt.tools.docsgen :as docsgen]))

;; ---- test-cli-spec: a representative fixture, not the real cli-spec ----
;;
;; render-cli-md is pure (spec -> markdown string); it has no compile-time
;; dependency on bases/cli's help.clj (components never depend on
;; bases -- Polylith's direction is the reverse, notes/ADRs.md ADR-0002),
;; so these tests exercise the renderer against a small, representative
;; spec of the same shape rather than importing the live one. The real
;; spec's own freshness against docs/cli.md is CI's generated-doc
;; freshness step (regenerate + `git diff --exit-code`), per this file's
;; own top docstring -- these tests were never that check; they prove
;; the renderer doesn't silently drop a group/verb/flag/exit-code that
;; *is* in whatever spec it's given.

(def test-cli-spec
  {:program "ehr"
   :exit-codes [{:code 0 :meaning "ran and passed"}
                {:code 1 :meaning "ran and legitimately rejected"}]
   :global-flags [{:flag "--json" :doc "emit a JSON projection" :default nil}]
   :groups [{:group "check" :doc "golden-equivalence judge"
             :positional "PATH" :positional-doc "a file or directory to check"
             :flags [{:flag "--expected" :doc "the corpus to compare against" :default nil}]}
            {:group "corpus" :doc "corpus construction"
             :verbs [{:verb "generate" :doc "generate a corpus"
                      :flags [{:flag "--seed" :doc "RNG seed" :default "1"}]}
                     {:verb "mutate" :doc "inject a controlled defect"
                      :positional "PATH" :positional-doc "a file or directory to mutate"
                      :flags []}]}]})

(defn- command-pairs
  [spec]
  (vec (mapcat (fn [g]
                 (if (:verbs g)
                   (map (fn [v] [(:group g) (:verb v)]) (:verbs g))
                   [[(:group g) nil]]))
               (:groups spec))))

;; ---- shared helpers ----

(deftest escape-cell-escapes-table-delimiters-test
  (is (= "a \\| b" (docsgen/escape-cell "a | b"))))

(deftest banner-names-its-target-and-what-to-edit-instead-test
  (let [b (docsgen/banner "operators-doc" "the registry" "Edit the registry.")]
    (is (str/starts-with? b "<!-- GENERATED by `make operators-doc` from the registry -- do not hand-edit."))
    (is (str/includes? b "Edit the registry."))))

;; ---- docs/operators.md ----

(deftest sorted-entries-are-ordered-by-format-then-id-test
  (let [entries (docsgen/sorted-entries)
        keys* (map (juxt :format :id) entries)]
    (is (= keys* (sort keys*)))))

(deftest operators-md-names-every-registered-operator-test
  (let [md (docsgen/render-operators-md (docsgen/sorted-entries))]
    (doseq [{:keys [id]} (operators/entries)]
      (is (str/includes? md (str "`" id "`")) (str id " must appear in docs/operators.md")))))

(deftest operators-md-carries-each-operators-doc-sentence-and-contract-test
  (let [md (docsgen/render-operators-md (docsgen/sorted-entries))]
    (doseq [{:keys [id doc contract]} (operators/entries)]
      (when doc
        (is (str/includes? md doc) (str id "'s :doc sentence must appear")))
      (is (str/includes? md (:target contract)) (str id "'s contract target must appear")))))

(deftest operators-md-has-one-section-per-registered-format-test
  (let [md (docsgen/render-operators-md (docsgen/sorted-entries))]
    (doseq [format (distinct (map :format (operators/entries)))]
      (is (str/includes? md (str "## " (docsgen/format-heading format) " operators"))
          (str format " must get its own section")))))

(deftest operators-md-carries-banner-and-pre-release-notice-test
  (let [md (docsgen/render-operators-md (docsgen/sorted-entries))]
    (is (str/starts-with? md "<!-- GENERATED by `make operators-doc`"))
    (is (str/includes? md docsgen/pre-release-notice))))

(deftest operators-md-points-at-calibration-and-locators-rather-than-restating-them-test
  (let [md (docsgen/render-operators-md (docsgen/sorted-entries))]
    (is (str/includes? md "(judge-calibration.md)"))
    (is (str/includes? md "(locators.md)"))))

(deftest operators-md-render-is-pure-and-idempotent-test
  (let [entries (docsgen/sorted-entries)]
    (is (= (docsgen/render-operators-md entries)
           (docsgen/render-operators-md entries)))))

;; ---- docs/cli.md ----

(deftest cli-md-names-every-group-and-verb-in-the-spec-test
  (let [md (docsgen/render-cli-md test-cli-spec)]
    (doseq [[group verb] (command-pairs test-cli-spec)]
      (if verb
        (is (str/includes? md (str "### `ehrt " group " " verb "`"))
            (str group " " verb " must get its own section"))
        (is (str/includes? md (str "## `ehrt " group "`"))
            (str group " must get its own section"))))))

(deftest cli-md-lists-every-flag-the-spec-declares-test
  (let [md (docsgen/render-cli-md test-cli-spec)
        spec-flags (concat (:global-flags test-cli-spec)
                           (mapcat (fn [g] (concat (:flags g) (mapcat :flags (:verbs g))))
                                   (:groups test-cli-spec)))]
    (is (seq spec-flags))
    (doseq [{:keys [flag doc]} spec-flags]
      (is (str/includes? md (str "`" flag "`")) (str flag " must appear"))
      (is (str/includes? md (docsgen/escape-cell doc)) (str flag "'s doc must appear")))))

(deftest cli-md-carries-the-exit-code-table-test
  (let [md (docsgen/render-cli-md test-cli-spec)]
    (doseq [{:keys [code meaning]} (:exit-codes test-cli-spec)]
      (is (str/includes? md (str "| `" code "` |")) (str "exit code " code " must appear"))
      (is (str/includes? md meaning)))))

(deftest cli-md-documents-positional-conventions-where-the-spec-declares-them-test
  (let [md (docsgen/render-cli-md test-cli-spec)]
    (doseq [g (:groups test-cli-spec)
            :when (:positional g)]
      (is (str/includes? md (str "**Positional argument `" (:positional g) "`**"))
          (str (:group g) " must document its positional argument"))
      (is (str/includes? md (:positional-doc g))))))

(deftest cli-md-carries-banner-and-pre-release-notice-test
  (let [md (docsgen/render-cli-md test-cli-spec)]
    (is (str/starts-with? md "<!-- GENERATED by `make cli-doc`"))
    (is (str/includes? md docsgen/pre-release-notice))))

(deftest cli-md-defers-worked-examples-to-the-other-reference-pages-test
  (testing "the author ruling: cli.md carries the surface, not walkthroughs"
    (let [md (docsgen/render-cli-md test-cli-spec)]
      (is (str/includes? md "(use-cases.md)"))
      (is (str/includes? md "(formats.md)"))
      (is (str/includes? md "(operators.md)"))
      (is (str/includes? md "(locators.md)")))))

(deftest cli-md-render-is-pure-and-idempotent-test
  (is (= (docsgen/render-cli-md test-cli-spec)
         (docsgen/render-cli-md test-cli-spec))))
