(ns ehrt.tools.operators-doc-test
  "Covers docs/operators.md's renderer (DOC-3). The real staleness
  guard is CI's generated-doc freshness step (.github/workflows/test.yml's
  \"generated-doc freshness (regen + diff)\" step, P1-2, 2026-07-31
  review catch-up: `make docsgen` then `git diff --exit-code` on all
  four generated docs, per push); these tests cover what that step
  can't -- that the renderer actually emits every registered operator,
  rather than emitting a well-formed page that happens to be missing
  half its data.

  Split out of the former ehrt.tools.docsgen-test (docs-tooling
  extraction, 2026-07-31, refactoring-review stage 1) alongside the
  namespace it covers: this half stayed in components/tools
  (ehrt.tools.operators-doc, unmoved -- it genuinely reaches into this
  component's own corpus.operators registry); the cli.md half moved to
  components/docs-tooling/test/ehrt/docs_tooling/docsgen_test.clj
  instead. escape-cell/banner are covered again here, against this
  component's own duplicate copy of those two helpers, not because the
  assertions themselves changed."
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is]]
            [ehrt.tools.corpus.operators :as operators]
            [ehrt.tools.operators-doc :as operators-doc]))

;; ---- shared helpers (this half's own duplicate copy) ----

(deftest escape-cell-escapes-table-delimiters-test
  (is (= "a \\| b" (operators-doc/escape-cell "a | b"))))

(deftest banner-names-its-target-and-what-to-edit-instead-test
  (let [b (operators-doc/banner "operators-doc" "the registry" "Edit the registry.")]
    (is (str/starts-with? b "<!-- GENERATED by `make operators-doc` from the registry -- do not hand-edit."))
    (is (str/includes? b "Edit the registry."))))

;; ---- docs/operators.md ----

(deftest sorted-entries-are-ordered-by-format-then-id-test
  (let [entries (operators-doc/sorted-entries)
        keys* (map (juxt :format :id) entries)]
    (is (= keys* (sort keys*)))))

(deftest operators-md-names-every-registered-operator-test
  (let [md (operators-doc/render-operators-md (operators-doc/sorted-entries))]
    (doseq [{:keys [id]} (operators/entries)]
      (is (str/includes? md (str "`" id "`")) (str id " must appear in docs/operators.md")))))

(deftest operators-md-carries-each-operators-doc-sentence-and-contract-test
  (let [md (operators-doc/render-operators-md (operators-doc/sorted-entries))]
    (doseq [{:keys [id doc contract]} (operators/entries)]
      (when doc
        (is (str/includes? md doc) (str id "'s :doc sentence must appear")))
      (is (str/includes? md (:target contract)) (str id "'s contract target must appear")))))

(deftest operators-md-has-one-section-per-registered-format-test
  (let [md (operators-doc/render-operators-md (operators-doc/sorted-entries))]
    (doseq [format (distinct (map :format (operators/entries)))]
      (is (str/includes? md (str "## " (operators-doc/format-heading format) " operators"))
          (str format " must get its own section")))))

(deftest operators-md-carries-banner-and-pre-release-notice-test
  (let [md (operators-doc/render-operators-md (operators-doc/sorted-entries))]
    (is (str/starts-with? md "<!-- GENERATED by `make operators-doc`"))
    (is (str/includes? md operators-doc/pre-release-notice))))

(deftest operators-md-points-at-calibration-and-locators-rather-than-restating-them-test
  (let [md (operators-doc/render-operators-md (operators-doc/sorted-entries))]
    (is (str/includes? md "(judge-calibration.md)"))
    (is (str/includes? md "(locators.md)"))))

(deftest operators-md-render-is-pure-and-idempotent-test
  (let [entries (operators-doc/sorted-entries)]
    (is (= (operators-doc/render-operators-md entries)
           (operators-doc/render-operators-md entries)))))
