(ns ehrt.tools.docsgen
  "Renderers for the two reference documents that are *derived data*
  rather than authored prose (DOC-3): docs/operators.md from the
  mutation-operator registry (ehrt.tools.corpus.operators), and
  docs/cli.md from a caller-supplied help spec shaped like
  bases/cli's own cli-spec. A sibling to ehrt.tools.pipeline and
  .usecases in exactly the way those two are siblings of each other:
  pure render-* functions assembling a markdown string, plus a thin
  `-X`-invokable write-*! shell. `render-cli-md` takes its spec as a
  plain argument rather than importing bases/cli's help.clj
  directly -- components never depend on bases (Polylith's dependency
  direction is the reverse) -- so this namespace has no compile-time
  knowledge of the CLI base at all; only a caller with access to both
  (e.g. a REPL, or a future dev-tooling base) can wire the two
  together.

  Both outputs are WHOLLY generated (author ruling, DOC-3): every word
  in docs/operators.md and docs/cli.md comes from here or from the data
  these functions read. There is no hand-edited region in either file,
  which is what lets CI's generated-doc freshness step regenerate and
  `git diff --exit-code` them alongside docs/pipeline.md and
  docs/use-cases.md. Preamble prose therefore lives as string literals
  below, the same way ehrt.tools.pipeline/render-pipeline-md's
  does.

  Determinism matters here in a way it doesn't for the pipeline
  renderers: `corpus.operators/entries` returns the vals of an atom-held
  map, whose order is not specified. Every listing below sorts by
  [format id] before rendering, so regeneration is byte-identical
  across runs and the freshness gate tests staleness rather than map
  iteration order."
  (:require [clojure.string :as str]
            [ehrt.tools.corpus.operators :as operators]))

;; ---- shared helpers ----

(def pre-release-notice
  "One line, in both generated docs' preambles (author ruling, DOC-3).
  Deliberately consistent with README.md's maturity language rather
  than a second, competing statement of the same thing."
  "**Pre-release.** Nothing in this repo has had a first release yet; the interfaces below may still move. See [`README.md`](../README.md#maturity) for the per-capability maturity table.")

(defn banner
  "The house \"generated file -- do not edit\" header block, in
  docs/pipeline.md's own form: what regenerates it, what to edit
  instead."
  [make-target source-description edit-instruction]
  (str "<!-- GENERATED by `make " make-target "` from " source-description " -- do not hand-edit.\n"
       "     " edit-instruction " -->\n"))

(defn escape-cell
  "Markdown table cells are pipe-delimited, so a `|` inside a flag's
  own doc string would silently split the cell. Nothing in the current
  spec or registry contains one -- this exists so that stops being a
  fact about today's data."
  [s]
  (str/replace (str s) "|" "\\|"))

(defn- table
  "headers is a vector of column names; rows a seq of same-length
  vectors. Cells are escaped; nil renders as an empty cell."
  [headers rows]
  (str/join "\n"
            (concat [(str "| " (str/join " | " headers) " |")
                     (str "|" (str/join "|" (repeat (count headers) "---")) "|")]
                    (map (fn [row] (str "| " (str/join " | " (map escape-cell row)) " |")) rows))))

(defn- exit-code-table
  [spec]
  (table ["Code" "Meaning"]
         (map (fn [{:keys [code meaning]}] [(str "`" code "`") meaning]) (:exit-codes spec))))

;; ---- docs/operators.md ----

(def format-headings
  "Display names for the format keywords the registry uses. A format
  not named here falls back to its own keyword name, so adding a third
  format to the registry produces a slightly plainer heading rather
  than a crash."
  {:fhir "FHIR" :v2 "HL7 v2"})

(defn format-heading
  [format]
  (get format-headings format (name format)))

(defn sorted-entries
  "Every registered operator, sorted by [format id] -- the same order
  `ehrt corpus operators` lists them in, so the doc and the verb can be
  read against each other line for line."
  []
  (sort-by (juxt :format :id) (operators/entries)))

(defn- operator-anchor-heading
  "`### :remove-required-element` -- version deliberately NOT in the
  heading. A heading anchor is a link target an assistant may have
  cited (AUTHORS-GUIDE.md section 6); bumping an operator to version
  \"2\" must not move the anchor out from under it."
  [{:keys [id]}]
  (str "### `" id "`\n"))

(defn- operator-detail
  [{:keys [id version doc locator-required? contract] :as entry}]
  (str (operator-anchor-heading entry)
       "\n" doc "\n\n"
       "- **Version:** `" version "` — pass as `--operator-version " version "`.\n"
       "- **Locator:** " (if locator-required?
                           "required — see [locators.md](locators.md) for the grammar this format accepts."
                           "not required.")
       "\n"
       "- **Contract:** `" (:type contract) "` — " (:target contract) "\n"))

(defn- operators-format-section
  "One `## <Format> operators` section, given the run of entries
  sharing that format. Takes the run rather than a [format entries]
  pair because `partition-by` (the caller) yields runs, and the
  format is already on every entry in one."
  [entries]
  (str "## " (format-heading (:format (first entries))) " operators\n\n"
       (table ["Operator" "Locator" "What it does"]
              (map (fn [{:keys [id doc locator-required?]}]
                     [(str "[`" id "`](#" (name id) ")")
                      (if locator-required? "required" "—")
                      doc])
                   entries))
       "\n\n"
       (str/join "\n" (map operator-detail entries))))

(defn render-operators-md
  "Pure: registry entries -> docs/operators.md's content. Entries are
  expected pre-sorted (see `sorted-entries`); this function does not
  re-sort, so a caller can render a filtered or reordered catalog in a
  test without fighting the function."
  [entries]
  (str (banner "operators-doc"
               "the mutation-operator registry in components/tools/src/ehrt/tools/corpus/operators.clj"
               "Edit the registry (or this file's renderer, components/tools/src/ehrt/tools/docsgen.clj) and regenerate instead.")
       "\n# Mutation operators\n\n"
       pre-release-notice "\n\n"
       "This is the catalog `ehrt corpus mutate` applies: every registered defect operator, "
       "what it does to a file, and which base-spec constraint the result violates. "
       "The same catalog is readable at the shell — `ehrt corpus operators`, or "
       "`ehrt corpus operators --format v2` for one format — and as EDN or JSON from that verb's output.\n\n"
       "Each operator is applied by id: `--operator-id <id> --operator-version <version>`, "
       "at one `--locator-path`, to every matching file under `PATH` (positional, or `--path`). "
       "See [cli.md](cli.md#ehrt-corpus-mutate) for the full flag list and "
       "[use-cases.md](use-cases.md) for which task calls for which operator.\n\n"
       "Two descriptions appear per operator, and they answer different questions. "
       "**What it does** is the edit — what changed in the file. "
       "**Contract** is the conformance claim — which constraint in the base specification "
       "the edited file now violates, which is what makes the operator useful as a test "
       "of whether a gate catches it.\n\n"
       (str/join "\n" (map operators-format-section (partition-by :format entries)))
       "\n## What this catalog does not tell you\n\n"
       "Whether a gate actually *convicts* a given mutant is a measured property, not a "
       "property of the operator. Every entry above was verified to convict at its format's "
       "current judge tier before being registered — and several plausible defects were "
       "probed, found not to convict, and dropped rather than shipped unconvictable. "
       "Those dropped candidates and the measured blind spots behind them are in "
       "[judge-calibration.md](judge-calibration.md), which is where to look when a gate "
       "result surprises you. They are not registry data, so they never appear in "
       "`ehrt corpus operators` output either.\n"))

;; ---- docs/cli.md ----

(defn- flags-table
  [flags]
  (if (seq flags)
    (table ["Flag" "Default" "Meaning"]
           (map (fn [{:keys [flag doc default]}]
                  [(str "`" flag "`") (if default (str "`" default "`") "—") doc])
                flags))
    "_No flags._"))

(defn- verb-section
  "A verb's own :positional/:positional-doc (D10) render the same way a
  group's do below -- declared per-verb rather than per-group because,
  unlike gate/check, not every verb in a group takes one."
  [group-name {:keys [verb doc flags positional positional-doc]}]
  (str "### `ehrt " group-name " " verb "`\n\n"
       doc "\n\n"
       (when positional
         (str "**Positional argument `" positional "`** — " positional-doc "\n\n"))
       (flags-table flags) "\n"))

(defn- group-section
  [{:keys [group doc positional positional-doc verbs flags]}]
  (str "## `ehrt " group "`\n\n"
       doc "\n\n"
       (when positional
         (str "**Positional argument `" positional "`** — " positional-doc "\n\n"))
       (if verbs
         (str/join "\n" (map #(verb-section group %) verbs))
         (str (flags-table flags) "\n"))))

(defn render-cli-md
  "Pure: the help spec -> docs/cli.md's content. Same spec `ehrt help`
  and `ehrt help <group>` render to plain text, so the page and the
  shell cannot drift apart -- there is one source, rendered twice."
  [spec]
  (str (banner "cli-doc"
               "the CLI help spec in bases/cli/src/ehrt/cli/help.clj"
               "Edit `cli-spec` (or this file's renderer, components/tools/src/ehrt/tools/docsgen.clj) and regenerate instead.")
       "\n# CLI reference\n\n"
       pre-release-notice "\n\n"
       "Every group, verb, and flag the `" (:program spec) "` command accepts. "
       "This page and `" (:program spec) " help` render the same spec, so the two cannot "
       "drift apart — reach for `" (:program spec) " help <group>` when you are already at a shell, "
       "and for this page when you are not.\n\n"
       (if (:doc spec) (str (:doc spec) "\n\n") "")
       "What this page deliberately does not carry: worked invocations. "
       "For \"what do I actually type for my task,\" see [use-cases.md](use-cases.md). "
       "For what `--report` writes and `--json` emits, see [formats.md](formats.md). "
       "For the mutation operators `ehrt corpus mutate` takes by id, see "
       "[operators.md](operators.md); for the locator strings it takes by path, see "
       "[locators.md](locators.md).\n\n"
       "## Synopsis\n\n"
       "```\n" (:program spec) " <group> [<verb>] [flags]\n```\n\n"
       (table ["Group" "What it covers"]
              (map (fn [g] [(str "[`" (:group g) "`](#ehrt-" (:group g) ")") (:doc g)]) (:groups spec)))
       "\n\n"
       "## Global flags\n\n"
       "Accepted anywhere in the command line, on any group or verb.\n\n"
       (flags-table (:global-flags spec)) "\n\n"
       "## Exit codes\n\n"
       "The same table every group's `" (:program spec) " help <group>` output ends with. "
       "These are the contract a CI job branches on.\n\n"
       (exit-code-table spec) "\n\n"
       (str/join "\n" (map group-section (:groups spec)))))

;; ---- impure shell (I/O) ----

(defn write-operators-md!
  "-X-invokable: renders the live operator registry to out (the
  Makefile's `operators-doc` target passes docs/operators.md).
  Requiring corpus.operators is what populates the registry -- the
  seed catalog registers itself at namespace load, the same
  registration-at-load-time convention corpus.canonicalizers uses."
  [{:keys [out]}]
  (spit out (render-operators-md (sorted-entries))))

(defn write-cli-md!
  "-X-invokable: renders a caller-supplied help spec to out. No longer
  called with an implicit default (the Makefile's `cli-doc` target did
  not survive the Polylith landing, notes/ADRs.md ADR-0002) -- `spec`
  is the CLI's own cli-spec, which the caller must supply, since
  components/tools cannot itself require bases/cli's help.clj
  (Polylith's dependency direction is base -> component, never the
  reverse)."
  [{:keys [out spec]}]
  (spit out (render-cli-md spec)))
