(ns ehrt.corpus.operators-doc
  "Renderer for docs/operators.md, the derived (DOC-3) reference for
  the mutation-operator registry (ehrt.corpus.operators). Split
  out of the former ehrt.tools.docsgen (docs-tooling extraction,
  2026-07-31, refactoring-review stage 1): that namespace's cli.md
  half (render-cli-md/write-cli-md!) was pure -- no dependency on
  anything in this component -- and moved to components/docs-tooling
  whole; this half genuinely reaches into corpus.operators' live
  registry, which would have made this component and docs-tooling
  require each other (docs-tooling needing this data back, this
  component already needing docs-tooling's write-cli-md! back) -- a
  real circular component dependency, a hard Clojure compile error,
  not a style question. Staying behind avoids it, and this is this
  component's own operator-doc renderer either way (its own Makefile
  target is `operators-doc`).

  Both this file and docs-tooling's own ehrt.docs-tooling.docsgen
  carry their own private copies of banner/escape-cell/table/
  exit-code-table -- the same handful of pure markdown-table helpers
  the original docsgen.clj shared across both halves. Duplicated
  rather than shared through an interface, since sharing them would
  reintroduce exactly the cross-brick coupling the split exists to
  avoid, for four small pure functions.

  Determinism matters here in a way it doesn't for the cli.md
  renderer: corpus.operators/entries returns the vals of an atom-held
  map, whose order is not specified. Every listing below sorts by
  [format id] before rendering, so regeneration is byte-identical
  across runs and the freshness gate tests staleness rather than map
  iteration order."
  (:require [clojure.string :as str]
            [ehrt.corpus.operators :as operators]))

;; ---- shared helpers (this half's own copy -- see docstring) ----

(def pre-release-notice
  "One line, in both generated docs' preambles (author ruling, DOC-3).
  Deliberately consistent with README.md's maturity language rather
  than a second, competing statement of the same thing."
  "**Pre-release.** Nothing in this repo has had a first release yet; the interfaces below may still move. See [`README.md`](../README.md#maturity) for the per-capability maturity table.")

(defn banner
  "The house \"generated file -- do not edit\" header block, in
  docs/pipeline.md's own form: what regenerates it, what to edit
  instead."
  [make-target source-description edit-instruction]
  (str "<!-- GENERATED by `make " make-target "` from " source-description " -- do not hand-edit.\n"
       "     " edit-instruction " -->\n"))

(defn escape-cell
  "Markdown table cells are pipe-delimited, so a `|` inside a flag's
  own doc string would silently split the cell. Nothing in the current
  spec or registry contains one -- this exists so that stops being a
  fact about today's data."
  [s]
  (str/replace (str s) "|" "\\|"))

(defn- table
  "headers is a vector of column names; rows a seq of same-length
  vectors. Cells are escaped; nil renders as an empty cell."
  [headers rows]
  (str/join "\n"
            (concat [(str "| " (str/join " | " headers) " |")
                     (str "|" (str/join "|" (repeat (count headers) "---")) "|")]
                    (map (fn [row] (str "| " (str/join " | " (map escape-cell row)) " |")) rows))))

;; ---- docs/operators.md ----

(def format-headings
  "Display names for the format keywords the registry uses. A format
  not named here falls back to its own keyword name, so adding a third
  format to the registry produces a slightly plainer heading rather
  than a crash."
  {:fhir "FHIR" :v2 "HL7 v2" :event "Event log"})

(defn format-heading
  [format]
  (get format-headings format (name format)))

(defn sorted-entries
  "Every registered operator, sorted by [format id] -- the same order
  `ehrt corpus operators` lists them in, so the doc and the verb can be
  read against each other line for line."
  []
  (sort-by (juxt :format :id) (operators/entries)))

(defn- operator-anchor-heading
  "`### :remove-required-element` -- version deliberately NOT in the
  heading. A heading anchor is a link target an assistant may have
  cited (AUTHORS-GUIDE.md section 6); bumping an operator to version
  \"2\" must not move the anchor out from under it."
  [{:keys [id]}]
  (str "### `" id "`\n"))

(defn- expected-findings-line
  "Event operators only (ADR-0176 section 2(i)). The finding set is the
  event analogue of `:contract`/`:target`, and it is a different KIND
  of claim: a target sentence is prose about a third-party
  specification, checkable only by reading it, while a finding set
  names invariants in this repository's OWN closed vocabulary, so the
  gate can assert observed = declared exactly. Rendered so a consumer
  reading this page knows what to expect `ehrt sim check` to say, not
  merely that something will be wrong."
  [{:keys [expected-findings]}]
  (when (seq expected-findings)
    (str "- **Expected findings:** "
         (str/join ", " (map #(str "`" % "`") (sort expected-findings)))
         " — what `ehrt sim check` reports on the mutant, exactly and nothing else.\n")))

(defn- operator-detail
  [{:keys [version doc locator-required? contract] :as entry}]
  (str (operator-anchor-heading entry)
       "\n" doc "\n\n"
       "- **Version:** `" version "` — pass as `--operator-version " version "`.\n"
       "- **Locator:** " (if locator-required?
                           "required — see [locators.md](locators.md) for the grammar this format accepts."
                           "not required.")
       "\n"
       "- **Contract:** `" (:type contract) "` — " (:target contract) "\n"
       (expected-findings-line entry)))

(defn- operators-format-section
  "One `## <Format> operators` section, given the run of entries
  sharing that format. Takes the run rather than a [format entries]
  pair because `partition-by` (the caller) yields runs, and the
  format is already on every entry in one."
  [entries]
  (str "## " (format-heading (:format (first entries))) " operators\n\n"
       (table ["Operator" "Locator" "What it does"]
              (map (fn [{:keys [id doc locator-required?]}]
                     [(str "[`" id "`](#" (name id) ")")
                      (if locator-required? "required" "—")
                      doc])
                   entries))
       "\n\n"
       (str/join "\n" (map operator-detail entries))))

(defn render-operators-md
  "Pure: registry entries -> docs/operators.md's content. Entries are
  expected pre-sorted (see `sorted-entries`); this function does not
  re-sort, so a caller can render a filtered or reordered catalog in a
  test without fighting the function."
  [entries]
  (str (banner "operators-doc"
               "the mutation-operator registry in components/corpus/src/ehrt/corpus/operators.clj"
               "Edit the registry (or this file's renderer, components/corpus/src/ehrt/corpus/operators_doc.clj) and regenerate instead.")
       "\n# Mutation operators\n\n"
       pre-release-notice "\n\n"
       "This is the defect-operator catalog: every registered operator, what it does to its "
       "input, and which constraint the result violates. "
       "The same catalog is readable at the shell — `ehrt corpus operators`, or "
       "`ehrt corpus operators --format v2` for one format — and as EDN or JSON from that verb's output.\n\n"
       "**Two layers, two verbs.** FHIR and HL7 v2 operators are FILE operators: `ehrt corpus mutate` "
       "applies them by id — `--operator-id <id> --operator-version <version>` — at one `--locator-path`, "
       "to every matching file under `PATH` (positional, or `--path`). They are lowering-layer faults: "
       "a blanked field, a truncated segment, a malformed date — defects that come into existence only "
       "when a record is written out as bytes. Event-log operators are different: they mutate the "
       "ground-truth EVENT LOG itself, before any of it is rendered, so every emitter downstream "
       "inherits one mutated truth. `ehrt sim mutate` applies them, by id and seed, as a filter — "
       "`ehrt sim run --format ground-truth | ehrt sim mutate --operator-id <id> --seed <n> | ehrt sim check`. "
       "See [cli.md](cli.md#ehrt-corpus-mutate) for the full flag list and "
       "[use-cases.md](use-cases.md) for which task calls for which operator.\n\n"
       "Two descriptions appear per operator, and they answer different questions. "
       "**What it does** is the edit — what changed in the input. "
       "**Contract** is the conformance claim — which constraint the edited input now violates, "
       "which is what makes the operator useful as a test of whether a gate catches it. "
       "Event-log operators carry a third: **Expected findings**, the invariants `ehrt sim check` "
       "reports on the mutant — exactly that set and nothing else, which is a machine-checked claim "
       "rather than a prose one, because the vocabulary is this repository's own.\n\n"
       (str/join "\n" (map operators-format-section (partition-by :format entries)))
       "\n## What this catalog does not tell you\n\n"
       "Whether a gate actually *convicts* a given mutant is a measured property, not a "
       "property of the operator. Every entry above was verified to convict at its format's "
       "current judge tier before being registered — and several plausible defects were "
       "probed, found not to convict, and dropped rather than shipped unconvictable. "
       "Those dropped candidates and the measured blind spots behind them are in "
       "[judge-calibration.md](judge-calibration.md), which is where to look when a gate "
       "result surprises you. They are not registry data, so they never appear in "
       "`ehrt corpus operators` output either.\n\n"
       "Event-log operators are the exception, and deliberately so. Their oracle is "
       "`ehrt sim check`, whose catalog this repository owns — so an event operator that "
       "nothing in that catalog convicts is evidence of a hole in the catalog, not a fact about "
       "a third-party validator. Such a candidate is refused registration outright and recorded "
       "as a catalog gap, rather than shipped with an empty claim.\n"))

;; ---- impure shell (I/O) ----

(defn write-operators-md!
  "-X-invokable: renders the live operator registry to out (the
  Makefile's `operators-doc` target passes docs/operators.md).
  Requiring corpus.operators is what populates the registry -- the
  seed catalog registers itself at namespace load, the same
  registration-at-load-time convention corpus.canonicalizers uses."
  [{:keys [out]}]
  (spit out (render-operators-md (sorted-entries))))
