(ns ehr-testing-tools.pipeline
  "Schema for the pipeline's own resource-equation data
  (docs/pipeline.edn, docs/notation.md, pattern nursery #13) -- the
  notation eats the repo's own dogfood: docs/pipeline.edn is authored
  EDN, and this namespace is what validates it. `docs/pipeline.md` is
  generated *from* docs/pipeline.edn via the string-diagram skill
  (`make pipeline`); this namespace has nothing to do with that
  rendering step, only with the source data's shape."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [malli.core :as m]))

(def stage-kinds
  "The five stage kinds (docs/notation.md) -- every stage in this
  repo's pipeline is exactly one of these."
  #{:transform :normalize :enrich :gate :feedback})

(def stage-statuses
  #{:built :planned})

(def Stage
  [:map
   [:id :keyword]
   [:label :string]
   [:kind (into [:enum] stage-kinds)]
   [:status (into [:enum] stage-statuses)]
   [:inputs [:vector :string]]
   [:outputs [:vector :string]]
   [:catalytic {:optional true} [:vector :string]]
   [:laws {:optional true} [:vector :string]]
   [:contract {:optional true} :string]])

(def Pipeline
  [:map
   [:schema-version [:= 1]]
   [:stages [:vector Stage]]])

(defn valid-stage?
  [stage]
  (m/validate Stage stage))

(defn valid?
  [pipeline]
  (m/validate Pipeline pipeline))

;; ---- rendering: docs/pipeline.edn -> the string-diagram skill's
;; equation-line grammar (docs/notation.md's equation form) ----

(defn stage->equation-line
  "Renders one stage as one string-diagram-skill equation line. A
  catalytic resource appears on both sides -- once in the LHS product
  (it's syntactically an input) and once in the {catalytic: ...}
  annotation (semantically unconsumed) -- this duplication is the
  skill's own grammar (see resource_equations_to_mermaid.py's
  parse_annotations), not a copy/paste mistake here."
  [{:keys [label inputs outputs catalytic]}]
  (let [lhs (str/join " × " (concat inputs catalytic))
        rhs (str/join " + " outputs)
        base (str lhs " → " rhs "  [" label "]")]
    (if (seq catalytic)
      (str base "  {catalytic: " (str/join ", " catalytic) "}")
      base)))

(defn pipeline->equations-text
  "Renders every stage in :stages to the skill's equation-line format,
  one per line. A :planned stage gets a leading comment line noting
  its status -- the skill ignores comment lines, so this is purely
  documentary in the rendered diagram, not a distinct visual state."
  [{:keys [stages]}]
  (str/join "\n"
            (mapcat (fn [{:keys [status] :as stage}]
                      (cond-> []
                        (= status :planned) (conj (str "# planned: " (:label stage)))
                        true (conj (stage->equation-line stage))))
                    stages)))

(defn render-pipeline-md
  "Pure assembly of docs/pipeline.md's content from already-rendered
  equations text and already-rendered mermaid text -- no I/O here;
  write-pipeline-md! below is the thin, impure shell around it."
  [{:keys [equations-text mermaid-text]}]
  (str "<!-- GENERATED by `make pipeline` from docs/pipeline.edn -- do not hand-edit.\n"
       "     Edit docs/pipeline.edn and regenerate instead. -->\n\n"
       "# Pipeline\n\n"
       "The repo's own pipeline, as resource equations (see "
       "[docs/notation.md](notation.md) for the notation) and the "
       "diagram mechanically derived from them. Source of truth: "
       "[docs/pipeline.edn](pipeline.edn).\n\n"
       "## Equations\n\n```\n" equations-text "\n```\n\n"
       "## Diagram\n\n```mermaid\n" (str/trim mermaid-text) "\n```\n"))

;; ---- impure shell (I/O) ----

(defn read-pipeline-edn
  [path]
  (edn/read-string (slurp path)))

(defn write-equations-txt!
  "-X-invokable: reads pipeline-edn (default docs/pipeline.edn), writes
  its rendered equations text to out."
  [{:keys [pipeline-edn out] :or {pipeline-edn "docs/pipeline.edn"}}]
  (spit out (pipeline->equations-text (read-pipeline-edn pipeline-edn))))

(defn write-pipeline-md!
  "-X-invokable: assembles docs/pipeline.md from the equations text and
  mermaid text already written to disk by the Makefile's `pipeline`
  target (the mermaid rendering step is the string-diagram skill's own
  Python script, not this namespace's job)."
  [{:keys [equations-txt mermaid out]}]
  (spit out (render-pipeline-md {:equations-text (slurp equations-txt)
                                  :mermaid-text (slurp mermaid)})))
