(ns ehr-testing-tools.usecases
  "Schema and renderer for the use-cases catalog's own data
  (docs/use-cases.edn, P6) -- a sibling to ehr-testing-tools.pipeline
  (docs/pipeline.edn), same split: this namespace validates the
  authored EDN and assembles already-rendered equations/mermaid text
  into docs/use-cases.md (`make use-cases`); it has nothing to do with
  actually running the string-diagram skill's python mermaid step,
  same as pipeline.clj's own render-pipeline-md.

  Unlike docs/pipeline.edn's :stages (full Malli-schema'd Stage
  records, one equation each), a use case's :equations is a vector of
  already-formatted equation-line strings -- most use cases reuse
  several of docs/pipeline.edn's own named stages verbatim (Generate,
  Mutate, Gate, ...) in one short sequence, so re-declaring each
  stage's full :kind/:status/:laws record per use case would be pure
  duplication; the equation-line text itself (the same grammar
  docs/notation.md defines) is the right unit here."
  (:require [clojure.edn :as edn]
            [clojure.string :as str]
            [malli.core :as m]))

(def maturities
  "Per-use-case honesty labels (distinct from README.md's per-
  capability maturity table): :usable (the equations below are
  exactly what's shipped, today); :experimental (shipped, interfaces
  may move); :illustrative (the pattern is real and composable from
  shipped stages, but no example pipeline ships it end-to-end);
  :planned (the equation names a resource/stage this repo doesn't
  fully support yet -- stated honestly in :get, not smoothed over)."
  #{:usable :experimental :illustrative :planned})

(def UseCase
  [:map
   [:id :keyword]
   [:title :string]
   [:audience :string]
   [:bring :string]
   [:get :string]
   [:maturity (into [:enum] maturities)]
   [:equations [:vector :string]]])

(def UseCases
  [:map
   [:schema-version [:= 1]]
   [:cases [:vector UseCase]]])

(defn valid-use-case?
  [use-case]
  (m/validate UseCase use-case))

(defn valid?
  [use-cases]
  (m/validate UseCases use-cases))

;; ---- rendering: docs/use-cases.edn -> docs/use-cases.md ----

(defn case->markdown-section
  "Renders one use case as a markdown section: title, the narrative
  fields (audience/bring/get/maturity), the raw equations block, and
  the case's own already-rendered mermaid diagram."
  [{:keys [title audience bring get maturity equations]} mermaid-text]
  (str "## " title "\n\n"
       "**Audience:** " audience "\n\n"
       "**You bring:** " bring "\n\n"
       "**You get:** " get "\n\n"
       "**Maturity:** " (name maturity) "\n\n"
       "```\n" (str/join "\n" equations) "\n```\n\n"
       "```mermaid\n" (str/trim mermaid-text) "\n```\n"))

(defn render-use-cases-md
  "Assembles docs/use-cases.md's full content from use-cases-data
  (docs/use-cases.edn, already read) and mermaid-by-id (a map of case
  :id -> that case's already-rendered mermaid text, produced by the
  string-diagram skill's python script, one small diagram per case).
  Throws (a programmer-error condition, not a result/rejected -- this
  is generator-time tooling, not a runtime capability) if a case's
  :id is missing from mermaid-by-id, so a `make use-cases` run fails
  loudly on a stale/incomplete mermaid set rather than silently
  omitting a case's diagram."
  [{:keys [cases]} mermaid-by-id]
  (str "<!-- GENERATED by `make use-cases` from docs/use-cases.edn -- do not hand-edit.\n"
       "     Edit docs/use-cases.edn and regenerate instead. -->\n\n"
       "# Use Cases\n\n"
       "What you can do with this repo, formally: one entry per use case, "
       "each anchored to the resource equations (`docs/notation.md`) it "
       "actually composes from `docs/pipeline.edn`'s own built stages. "
       "An `{external: true}` stage in a case's equations names a "
       "black-box component the use case's own author fills in -- code "
       "this repo doesn't implement and makes no claim about; a "
       "`{spider: funnel}` merge node is a union resource "
       "(`docs/notation.md`) wherever a case's sources genuinely vary. "
       "Maturity here is a per-use-case honesty label distinct from "
       "`README.md`'s per-capability table -- see the header comment of "
       "`docs/use-cases.edn` for what each label means.\n\n"
       (str/join "\n" (map (fn [{:keys [id] :as use-case}]
                              (if-let [mermaid (get mermaid-by-id id)]
                                (case->markdown-section use-case mermaid)
                                (throw (ex-info (str "no mermaid text for use case " id) {:id id}))))
                            cases))))

;; ---- impure shell (I/O) ----

(defn read-use-cases-edn
  [path]
  (edn/read-string (slurp path)))

(defn write-case-equations!
  "-X-invokable: reads use-cases-edn (default docs/use-cases.edn),
  writes each case's own equations text to out-dir/<id>.txt (one file
  per case, so the Makefile can run the python mermaid step once per
  file, exactly as `make pipeline` already does for the single
  pipeline-wide equations file)."
  [{:keys [use-cases-edn out-dir] :or {use-cases-edn "docs/use-cases.edn"}}]
  (let [{:keys [cases]} (read-use-cases-edn use-cases-edn)]
    (doseq [{:keys [id equations]} cases]
      (spit (str out-dir "/" (name id) ".txt") (str/join "\n" equations)))))

(defn write-use-cases-md!
  "-X-invokable: assembles docs/use-cases.md from docs/use-cases.edn
  and the per-case mermaid files already written to cases-dir by the
  Makefile's `use-cases` target (<id>.mermaid per case, produced by
  the string-diagram skill's own python script -- not this
  namespace's job, same split as write-pipeline-md!)."
  [{:keys [use-cases-edn cases-dir out] :or {use-cases-edn "docs/use-cases.edn"}}]
  (let [data (read-use-cases-edn use-cases-edn)
        mermaid-by-id (into {} (map (fn [{:keys [id]}]
                                       [id (slurp (str cases-dir "/" (name id) ".mermaid"))]))
                             (:cases data))]
    (spit out (render-use-cases-md data mermaid-by-id))))
