(ns ehrt.docs-tooling.docsgen
  "Renderer for docs/cli.md, the derived (DOC-3) reference for the
  CLI's own help spec. A sibling to ehrt.docs-tooling.pipeline and
  .usecases in exactly the way those two are siblings of each other:
  pure render-* functions assembling a markdown string, plus a thin
  `-X`-invokable write-*! shell. `render-cli-md` takes its spec as a
  plain argument rather than importing bases/cli's help.clj
  directly -- components never depend on bases (Polylith's dependency
  direction is the reverse) -- so this namespace has no compile-time
  knowledge of the CLI base at all; only a caller with access to both
  (e.g. a REPL, or a future dev-tooling base) can wire the two
  together.

  Split out of the former ehrt.tools.docsgen (docs-tooling extraction,
  2026-07-31, refactoring-review stage 1): that namespace's other
  half, docs/operators.md's renderer, genuinely reached into
  the domain component's own corpus.operators registry, which would
  have made this component and that one require each other -- a real
  circular component dependency (it needed this file's own
  write-cli-md! back at the time), a hard Clojure compile error, not a
  style question. This half is pure (spec argument in, string out), so
  it moved whole; the operators.md half stayed in the domain component
  (components/tools then, components/corpus since stage 3), renamed
  ehrt.corpus.operators-doc.

  The output is WHOLLY generated (author ruling, DOC-3): every word in
  docs/cli.md comes from here or from the spec this function is given.
  There is no hand-edited region, which is what lets CI's generated-doc
  freshness step regenerate and `git diff --exit-code` it alongside
  docs/pipeline.md, docs/use-cases.md, and docs/operators.md. Preamble
  prose therefore lives as string literals below, the same way
  ehrt.docs-tooling.pipeline/render-pipeline-md's does.

  This file carries its own private copy of banner/escape-cell/table/
  exit-code-table -- the same handful of pure markdown-table helpers
  ehrt.corpus.operators-doc also carries, from the original docsgen.clj
  the two halves split from. Duplicated rather than shared through an
  interface, since sharing them would reintroduce exactly the
  cross-brick coupling the split exists to avoid, for four small pure
  functions."
  (:require [clojure.string :as str]))

;; ---- shared helpers (this half's own copy -- see docstring) ----

(def pre-release-notice
  "One line, in both generated docs' preambles (author ruling, DOC-3).
  Deliberately consistent with README.md's maturity language rather
  than a second, competing statement of the same thing."
  "**Pre-release.** Nothing in this repo has had a first release yet; the interfaces below may still move. See [`README.md`](../README.md#maturity) for the per-capability maturity table.")

(defn banner
  "The house \"generated file -- do not edit\" header block, in
  docs/pipeline.md's own form: what regenerates it, what to edit
  instead."
  [make-target source-description edit-instruction]
  (str "<!-- GENERATED by `make " make-target "` from " source-description " -- do not hand-edit.\n"
       "     " edit-instruction " -->\n"))

(defn escape-cell
  "Markdown table cells are pipe-delimited, so a `|` inside a flag's
  own doc string would silently split the cell. Nothing in the current
  spec or registry contains one -- this exists so that stops being a
  fact about today's data."
  [s]
  (str/replace (str s) "|" "\\|"))

(defn- table
  "headers is a vector of column names; rows a seq of same-length
  vectors. Cells are escaped; nil renders as an empty cell."
  [headers rows]
  (str/join "\n"
            (concat [(str "| " (str/join " | " headers) " |")
                     (str "|" (str/join "|" (repeat (count headers) "---")) "|")]
                    (map (fn [row] (str "| " (str/join " | " (map escape-cell row)) " |")) rows))))

(defn- exit-code-table
  [spec]
  (table ["Code" "Meaning"]
         (map (fn [{:keys [code meaning]}] [(str "`" code "`") meaning]) (:exit-codes spec))))

;; ---- docs/cli.md ----

(defn- flags-table
  [flags]
  (if (seq flags)
    (table ["Flag" "Default" "Meaning"]
           (map (fn [{:keys [flag doc default]}]
                  [(str "`" flag "`") (if default (str "`" default "`") "—") doc])
                flags))
    "_No flags._"))

(defn- verb-section
  "A verb's own :positional/:positional-doc (D10) render the same way a
  group's do below -- declared per-verb rather than per-group because,
  unlike gate/check, not every verb in a group takes one."
  [group-name {:keys [verb doc flags positional positional-doc]}]
  (str "### `ehrt " group-name " " verb "`\n\n"
       doc "\n\n"
       (when positional
         (str "**Positional argument `" positional "`** — " positional-doc "\n\n"))
       (flags-table flags) "\n"))

(defn- group-section
  [{:keys [group doc positional positional-doc verbs flags]}]
  (str "## `ehrt " group "`\n\n"
       doc "\n\n"
       (when positional
         (str "**Positional argument `" positional "`** — " positional-doc "\n\n"))
       (if verbs
         (str/join "\n" (map #(verb-section group %) verbs))
         (str (flags-table flags) "\n"))))

(defn render-cli-md
  "Pure: the help spec -> docs/cli.md's content. Same spec `ehrt help`
  and `ehrt help <group>` render to plain text, so the page and the
  shell cannot drift apart -- there is one source, rendered twice."
  [spec]
  (str (banner "cli-doc"
               "the CLI help spec in bases/cli/src/ehrt/cli/help.clj"
               "Edit `cli-spec` (or this file's renderer, components/docs-tooling/src/ehrt/docs_tooling/docsgen.clj) and regenerate instead.")
       "\n# CLI reference\n\n"
       pre-release-notice "\n\n"
       "Every group, verb, and flag the `" (:program spec) "` command accepts. "
       "This page and `" (:program spec) " help` render the same spec, so the two cannot "
       "drift apart — reach for `" (:program spec) " help <group>` when you are already at a shell, "
       "and for this page when you are not.\n\n"
       (if (:doc spec) (str (:doc spec) "\n\n") "")
       "What this page deliberately does not carry: worked invocations. "
       "For \"what do I actually type for my task,\" see [use-cases.md](use-cases.md). "
       "For what `--report` writes and `--json` emits, see [formats.md](formats.md). "
       "For the mutation operators `ehrt corpus mutate` takes by id, see "
       "[operators.md](operators.md); for the locator strings it takes by path, see "
       "[locators.md](locators.md).\n\n"
       "## Synopsis\n\n"
       "```\n" (:program spec) " <group> [<verb>] [flags]\n```\n\n"
       (table ["Group" "What it covers"]
              (map (fn [g] [(str "[`" (:group g) "`](#ehrt-" (:group g) ")") (:doc g)]) (:groups spec)))
       "\n\n"
       "## Global flags\n\n"
       "Accepted anywhere in the command line, on any group or verb.\n\n"
       (flags-table (:global-flags spec)) "\n\n"
       "## Exit codes\n\n"
       "The same table every group's `" (:program spec) " help <group>` output ends with. "
       "These are the contract a CI job branches on.\n\n"
       (exit-code-table spec) "\n\n"
       (str/join "\n" (map group-section (:groups spec)))))

;; ---- impure shell (I/O) ----

(defn write-cli-md!
  "-X-invokable: renders a caller-supplied help spec to out. No longer
  called with an implicit default (the Makefile's `cli-doc` target did
  not survive the Polylith landing, notes/ADRs.md ADR-0002) -- `spec`
  is the CLI's own cli-spec, which the caller must supply, since
  components/docs-tooling cannot itself require bases/cli's help.clj
  (Polylith's dependency direction is base -> component, never the
  reverse)."
  [{:keys [out spec]}]
  (spit out (render-cli-md spec)))
