(ns ehrt.tools.corpus.intake
  "Intake capability (P5): foreign corpora -- files a consuming team
  brings from their own pipeline, not generated by this repo's own
  corpus.generate -- become first-class citizens of the same
  lineage/content-hash design generated corpora already use. Nursery
  #8 (corpus catalog): an index of corpus items (id, layer, format,
  lineage ref, tags); meaning lives in data, not filenames.

  Format sniffing is a cheap heuristic, not a validator: a file tagged
  :fhir-json here has merely been observed to parse as JSON with a
  top-level \"resourceType\" key -- judge.fhir, not this namespace, is
  what actually judges conformance. Content hashing is format-aware
  so an intaken FHIR file's catalog :id is *the same* hash
  corpus.mutate independently computes as a mutant's :parent -- no
  adapter, no translation layer between intake and mutation; the two
  consume the same content-identity function, so lineage chains
  across the intake/mutate boundary unchanged.

  Manifest sidecars (ADR-0014): a directory may carry an optional
  manifest.edn alongside the files it describes. When one is present
  and validates against corpus.manifest/ManifestV1_1, every catalog
  entry for a file in that SAME directory (manifest.edn's own entry
  included -- no special-casing) gains :provenance, the manifest's
  identity fields. This is generator-agnostic: nothing here knows
  about any particular producer, sim included -- any pipeline that
  drops a ManifestV1_1-shaped manifest.edn beside its output gets the
  same treatment. An absent or invalid sidecar leaves the catalog
  byte-identical to a run with no sidecar at all; an invalid one is
  recorded as an intake-record :note, never an error -- enrich-kind:
  intake adds fields, it never alters or rejects on what it finds."
  (:require [clojure.data.json :as json]
            [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [malli.core :as m]
            [ehrt.tools.corpus.manifest :as manifest]
            [ehrt.tools.corpus.operation-manifest :as operation-manifest]
            [ehrt.tools.corpus.mutate :as mutate]
            [ehrt.tools.corpus.source-sink :as source-sink]
            [ehrt.kernel.interface :as kernel])
  (:import [java.io File]))

(def known-source-formats #{:fhir-json :v2-er7 :unknown})

(def Provenance
  [:map
   [:schema-version :string]
   [:stage :keyword]
   [:generator [:map
                [:name :string]
                [:version :string]
                [:sha256 [:re #"^[0-9a-f]{64}$"]]]]
   [:seeds [:map-of :keyword :int]]])

(def OperationProvenance
  "The operation-manifest.edn sidecar's own enrichment shape (SS-4b,
  D-d resolved via ADR-0020) -- symmetric to Provenance above, never
  merged into it: :origin carries the OperationManifestV1's own
  :producer claim (this repo's honest identity, not an intake batch's
  :origin label -- a different field entirely, despite the shared
  word), :operation its :operation, :written-at its :written-at, and
  :input-hash (optional, present iff the manifest's own :items named
  this file with one) the content hash of whatever this file was
  derived from."
  [:map
   [:origin [:map [:name :string] [:identity :string] [:git :string]]]
   [:operation [:map [:kind :keyword] [:operator-id :keyword]
                [:operator-version :string] [:locator :map]]]
   [:written-at :string]
   [:input-hash {:optional true} [:re #"^[0-9a-f]{64}$"]]])

(def CatalogEntry
  "D-c (docs/source-sink-design.md D6, resolved 2026-07-28, SS-1
  Step 5): :source renamed to :origin. The field is a provenance label
  (an intake batch's source-label, e.g. \"acme-pipeline\") -- it always
  was, but the word :source now belongs to the formal Source type
  (ehrt.tools.corpus.source-sink), and a data-layer label
  wearing the same word as a runtime type is exactly the abstraction
  incoherence ADR-0009's :policy -> :disposition rename already exists
  to prevent (docs/source-sink-design.md Part VI). No compatibility
  alias for the old :source spelling -- pre-release (ADR-0008), same
  reasoning as D10's no-aliases.

  :provenance (ManifestV1_1 sidecar) and :operation-provenance
  (OperationManifestV1 sidecar, SS-4b) are mutually exclusive per
  directory -- corpus.intake rejects a directory carrying both
  sidecars :ambiguous-sidecars rather than ever setting both fields on
  the same entry."
  [:map
   [:id [:re #"^[0-9a-f]{64}$"]]
   [:path :string]
   [:format (into [:enum] known-source-formats)]
   [:layer [:= :foreign]]
   [:origin :string]
   [:received :string]
   [:provenance {:optional true} Provenance]
   [:operation-provenance {:optional true} OperationProvenance]])

(def IntakeRecord
  "D-c follow-up (2026-07-28, SS-2 Step 0): :source renamed to :origin,
  the same word freed by CatalogEntry's own D6 rename above -- this
  field is a distinct schema from CatalogEntry (this is the one
  batch-level record, not a per-file entry), so it was not itself named
  by D6/ADR-0017 decision 5, but a checker pass over SS-1 found it
  carrying the same collision by coincidence of spelling, not design.
  No compatibility alias, same reasoning as CatalogEntry's rename."
  [:map
   [:origin :string]
   [:date :string]
   [:file-count :int]
   [:catalog-hash [:re #"^[0-9a-f]{64}$"]]
   [:notes {:optional true}
    [:vector [:map [:type :keyword] [:dir :string] [:reason :string]]]]])

(defn valid-catalog-entry?
  [entry]
  (m/validate CatalogEntry entry))

(defn valid-intake-record?
  [record]
  (m/validate IntakeRecord record))

;; ---- format sniff: cheap heuristics, recorded not trusted ----

(defn- fhir-json?
  [content]
  (try
    (let [parsed (json/read-str content)]
      (and (map? parsed) (contains? parsed "resourceType")))
    (catch Exception _ false)))

(defn- v2-er7?
  "MSH-led ER7 encoding: an MSH segment starts with the literal \"MSH\"
  immediately followed by its own field separator (canonically \"|\",
  but ER7 allows any non-alphanumeric byte there) -- checking the 4th
  character is non-alphanumeric is enough to distinguish a real MSH
  segment from incidental text starting with the letters \"MSH\"."
  [content]
  (and (str/starts-with? content "MSH")
       (> (count content) 3)
       (not (Character/isLetterOrDigit (.charAt ^String content 3)))))

(defn sniff-format
  "Cheap, unvalidating format heuristic over a file's raw text content:
  :fhir-json (parses as JSON, top-level \"resourceType\" key present),
  :v2-er7 (starts with an MSH segment, ER7-encoded), or :unknown.
  Recorded, not trusted -- judge.fhir/judge.v2 are the actual judges of
  conformance; this only routes a file to the right catalog bucket."
  [content]
  (cond
    (fhir-json? content) :fhir-json
    (v2-er7? content) :v2-er7
    :else :unknown))

;; ---- content hash: format-aware, chains into corpus.mutate's own
;; content-identity function for the one format that already has one ----

(defn content-hash
  "The catalog :id for a file's content, dispatched by sniffed format.
  :fhir-json uses corpus.mutate/content-hash (sha256 of the parsed
  data's canonical-JSON serialization) -- the exact function
  corpus.mutate itself calls to compute a mutant's lineage :parent --
  so an intaken FHIR file's catalog id and its eventual mutant's
  :parent are the same value with no adapter. Every other format
  hashes the file's raw bytes directly: no canonical parsed form
  exists for v2 or unknown content yet (v2 mutation is P6)."
  [content format]
  (case format
    :fhir-json (mutate/content-hash (json/read-str content))
    (kernel/sha256-string content)))

;; ---- intake! ----

(defn- source-files
  "Every regular file under dir, recursively, sorted by path for a
  deterministic catalog ordering -- foreign corpora may nest into
  subdirectories, unlike this repo's own flat generated output trees."
  [dir]
  (->> (file-seq (io/file dir))
       (filter #(.isFile ^File %))
       (sort-by #(.getPath ^File %))))

(defn- relative-path
  "file's path relative to source-dir, forward-slash-joined
  regardless of host path separator -- the catalog is a portable
  record, not tied to the orchestrating host's filesystem conventions."
  [source-dir file]
  (let [root (str (.getCanonicalPath (io/file source-dir)) File/separator)
        full (.getCanonicalPath ^File file)
        rel (if (str/starts-with? full root) (subs full (count root)) full)]
    (str/replace rel File/separator "/")))

(defn- relative-dir-path
  "Like relative-path, but for a directory -- source-dir itself relative
  to source-dir is \".\" (relative-path's own root-vs-full comparison
  only handles a *descendant*, since it looks for source-dir plus a
  trailing separator as a prefix)."
  [source-dir dir]
  (let [root (.getCanonicalPath (io/file source-dir))
        full (.getCanonicalPath ^File dir)]
    (if (= root full) "." (relative-path source-dir dir))))

;; ---- manifest sidecars (ADR-0014) ----

(defn- sidecar-result
  "manifest.edn in dir, if any: {:valid? true :manifest m} when it
  parses and conforms to corpus.manifest/ManifestV1_1, {:valid? false
  :reason \"...\"} for a parse failure or a schema mismatch (malli's own
  explain, so the reason names exactly what didn't conform), or nil
  when no manifest.edn is there at all."
  [dir]
  (let [mf (io/file dir "manifest.edn")]
    (when (.isFile mf)
      (try
        (let [parsed (edn/read-string (slurp mf))]
          (if (manifest/valid-v1-1? parsed)
            {:valid? true :manifest parsed}
            {:valid? false
             :reason (str "manifest.edn does not conform to ManifestV1_1: "
                          (pr-str (m/explain manifest/ManifestV1_1 parsed)))}))
        (catch Exception e
          {:valid? false :reason (str "manifest.edn failed to parse: " (or (ex-message e) (str e)))})))))

(defn- provenance-fields
  [manifest]
  (select-keys manifest [:schema-version :stage :generator :seeds]))

;; ---- operation-manifest.edn sidecars (SS-4b, D-d resolved via
;; ADR-0020, docs/source-sink-design.md Part III.5): a second,
;; symmetric sidecar mechanism -- same directory-scoped lookup as
;; manifest.edn above, its own recognizer, its own enrichment field
;; (:operation-provenance, never :provenance), never both in the same
;; directory (enforced in intake! below, not here). ----

(defn- operation-manifest-sidecar-result
  "operation-manifest.edn in dir, if any -- same {:valid? ...} shape as
  sidecar-result above, validated against
  ehrt.tools.corpus.operation-manifest/OperationManifestV1
  instead of ManifestV1_1."
  [dir]
  (let [mf (io/file dir "operation-manifest.edn")]
    (when (.isFile mf)
      (try
        (let [parsed (edn/read-string (slurp mf))]
          (if (operation-manifest/valid? parsed)
            {:valid? true :manifest parsed}
            {:valid? false
             :reason (str "operation-manifest.edn does not conform to OperationManifestV1: "
                          (pr-str (m/explain operation-manifest/OperationManifestV1 parsed)))}))
        (catch Exception e
          {:valid? false :reason (str "operation-manifest.edn failed to parse: " (or (ex-message e) (str e)))})))))

(defn- operation-provenance-fields
  "The :operation-provenance value for one file: :origin/:operation/
  :written-at apply uniformly (directory-wide, like Provenance's own
  fields above), :input-hash is per-item -- looked up in the manifest's
  own :items by this file's basename (the file's own path relative to
  its immediate parent directory, which is also where
  operation-manifest.edn sits -- the same directory-scoped assumption
  ADR-0014 already makes for manifest.edn), present only when that item
  actually named one."
  [manifest file-basename]
  (let [item (first (filter #(= file-basename (:name %)) (:items manifest)))]
    (cond-> {:origin (:producer manifest)
             :operation (:operation manifest)
             :written-at (:written-at manifest)}
      (:input-hash item) (assoc :input-hash (:input-hash item)))))

(defn- ambiguous-sidecar-dirs
  "Directories (among files' own immediate parents) where BOTH
  manifest.edn and operation-manifest.edn are present -- checked by
  raw file existence, independent of either one's own validity, since
  a directory claiming two producers for the same bytes is a defect
  regardless of whether either claim happens to parse."
  [files source-dir]
  (->> files
       (map #(.getParentFile ^File %))
       distinct
       (filter (fn [dir]
                 (and (.isFile (io/file dir "manifest.edn"))
                      (.isFile (io/file dir "operation-manifest.edn")))))
       (map #(relative-dir-path source-dir %))
       vec))

(defn- catalog-entry
  [file source-dir source-label received sidecar-fn op-sidecar-fn]
  (let [content (slurp file)
        format (sniff-format content)
        base {:id (content-hash content format)
              :path (relative-path source-dir file)
              :format format
              :layer :foreign
              :origin source-label
              :received received}
        parent (.getParentFile ^File file)
        sidecar (sidecar-fn parent)
        op-sidecar (op-sidecar-fn parent)]
    (cond
      (and sidecar (:valid? sidecar))
      (assoc base :provenance (provenance-fields (:manifest sidecar)))

      (and op-sidecar (:valid? op-sidecar))
      (assoc base :operation-provenance
             (operation-provenance-fields (:manifest op-sidecar) (.getName file)))

      :else base)))

(defn- invalid-sidecar-notes
  "One dedup'd :invalid-manifest-sidecar note per directory (among
  files' own directories) whose manifest.edn is present but invalid --
  never one per file, since it's the same sidecar failing the same way
  for every file it covers."
  [files source-dir sidecar-fn]
  (->> files
       (map #(.getParentFile ^File %))
       distinct
       (keep (fn [dir]
               (let [sidecar (sidecar-fn dir)]
                 (when (and sidecar (not (:valid? sidecar)))
                   {:type :invalid-manifest-sidecar
                    :dir (relative-dir-path source-dir dir)
                    :reason (:reason sidecar)}))))
       vec))

(defn- invalid-operation-manifest-sidecar-notes
  "Symmetric to invalid-sidecar-notes above, for operation-manifest.edn."
  [files source-dir op-sidecar-fn]
  (->> files
       (map #(.getParentFile ^File %))
       distinct
       (keep (fn [dir]
               (let [sidecar (op-sidecar-fn dir)]
                 (when (and sidecar (not (:valid? sidecar)))
                   {:type :invalid-operation-manifest-sidecar
                    :dir (relative-dir-path source-dir dir)
                    :reason (:reason sidecar)}))))
       vec))

(defn intake!
  "Catalogs every file under :source-dir as a foreign-corpus entry:
  content hash (format-aware, see `content-hash`), format sniff,
  {:layer :foreign :origin source-label :received}, plus :provenance
  when the file's own directory carries a validating manifest.edn
  sidecar (ADR-0014), or :operation-provenance when it carries a
  validating operation-manifest.edn sidecar instead (SS-4b, D-d
  resolved via ADR-0020) -- never both: a directory presenting BOTH
  sidecars is rejected kernel/rejected :ambiguous-sidecars before any
  catalog or intake-record is written, naming every offending directory
  (relative to :source-dir), never resolved by precedence. Writes
  :out/catalog.edn (the vector of entries) and :out/intake-record.edn
  (one batch record: origin, date, file count, the sha256 of the
  catalog file's own persisted bytes -- hashing what's actually
  written, same discipline as corpus.mutate's content-hash -- and
  :notes when any sidecar present was invalid, either kind).

  :received is a required, explicit date string -- never read from
  the wall clock here, matching corpus.generate's :reference-date
  discipline (a required, explicit, pinned input rather than ambient
  state); the CLI shell is where wall-clock defaulting belongs, not
  this core function.

  Returns kernel/ok {:catalog [...] :intake-record {...} :out}, or
  kernel/rejected :ambiguous-sidecars {:dirs [...]}."
  [{:keys [source-dir source-label out received]}]
  (let [files (source-files source-dir)
        ambiguous (ambiguous-sidecar-dirs files source-dir)]
    (if (seq ambiguous)
      (kernel/rejected :ambiguous-sidecars
                        {:dirs ambiguous
                         :hint "a directory with both manifest.edn and operation-manifest.edn claims two producers for the same bytes -- remove one"})
      (let [sidecar-fn (memoize sidecar-result)
            op-sidecar-fn (memoize operation-manifest-sidecar-result)
            catalog (mapv #(catalog-entry % source-dir source-label received sidecar-fn op-sidecar-fn) files)
            notes (into (invalid-sidecar-notes files source-dir sidecar-fn)
                        (invalid-operation-manifest-sidecar-notes files source-dir op-sidecar-fn))
            out-dir (io/file out)]
        (.mkdirs out-dir)
        (let [catalog-file (io/file out-dir "catalog.edn")]
          (spit catalog-file (pr-str catalog))
          (let [record (cond-> {:origin source-label
                                :date received
                                :file-count (count catalog)
                                :catalog-hash (kernel/sha256-file catalog-file)}
                         (seq notes) (assoc :notes notes))]
            (spit (io/file out-dir "intake-record.edn") (pr-str record))
            (kernel/ok {:catalog catalog :intake-record record :out out})))))))

(defn intake-via-source!
  "Like intake!, but takes a :dir Source value
  (ehrt.tools.corpus.source-sink) in place of a bare
  :source-dir string -- the door SS-1 gives every Source-typed caller
  (D1/D7, docs/source-sink-design.md: intake stays the single
  ingestion door, unchanged in role, gains callers). No behavior
  change: a :dir Source's :path IS the directory intake! would have
  walked directly, so this is a thin translation, not a
  reimplementation -- proven byte-identical against the pre-SS-1 call
  shape by the golden-catalog comparison (test-integration/
  ehrt/tools/intake_source_golden_test.clj (now projects/conformance/test/), SS-1 Step 4).

  Only :dir is accepted this session (SS-1's own scope fence, ruling
  8) -- any other :kind is rejected :unsupported-source-kind, the same
  vocabulary ehrt.tools.corpus.source-sink-url uses, even
  though this function never touches URLs itself. A :dir map that
  fails Source's own schema is rejected :invalid-source."
  [{:keys [source source-label out received]}]
  (if (not= :dir (:kind source))
    (kernel/rejected :unsupported-source-kind
                      {:kind (:kind source)
                       :hint "only :dir sources are supported this session -- SS-2/SS-3/SS-5 land the rest"})
    ;; Re-validated through source-sink/dir-source's own DirSource
    ;; schema (not just the generic, kind-open Source schema): a bare
    ;; {:kind :dir} with no :path is a valid *Source* but not a valid
    ;; *DirSource* -- this is the check that actually catches it,
    ;; rather than reaching intake!'s own source-files with a nil dir.
    (let [validated (source-sink/dir-source source)]
      (if-not (kernel/ok? validated)
        (kernel/rejected :invalid-source {:source source :explain validated})
        (intake! {:source-dir (:path (:payload validated))
                  :source-label source-label :out out :received received})))))
